(() => {
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cls=v=>v>=80?'ok':v>=60?'warn':v>=40?'risk':'crit';
const color=v=>v>=80?'#2e9b4b':v>=60?'#eab308':v>=40?'#f97316':'#ef4444';
const label=v=>v>=80?'Bom / Conforme':v>=60?'Atenção':v>=40?'Risco':'Crítico';
let mode='SGQ';
function installStyle(){if($('brMapStyle'))return;const s=document.createElement('style');s.id='brMapStyle';s.textContent=`.br-map-block{display:grid;grid-template-columns:minmax(0,8fr) minmax(250px,4fr);gap:12px}.br-map-card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:15px}.br-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.br-head h2{margin:0;font-size:22px}.br-head p{margin:4px 0 0;color:var(--muted)}.br-mode{display:flex;gap:6px;flex-wrap:wrap}.br-mode .active{background:var(--accent);color:#fff}.br-map-wrap{position:relative;min-height:500px;margin-top:12px;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:radial-gradient(circle at 50% 45%,rgba(22,134,255,.12),transparent 58%),var(--panel2)}.br-map-svg{width:100%;height:500px;display:block}.br-outline{fill:#17304c;stroke:#3a526e;stroke-width:2}.br-node{cursor:pointer}.br-node circle{stroke-width:3}.br-node text{fill:#fff;text-anchor:middle;font-weight:800}.br-node .n1{font-size:13px}.br-node .n2{font-size:20px}.br-node .n3{font-size:10px;fill:#cbd5e1}.br-side{display:grid;gap:9px;align-content:start}.br-kpi{text-align:center;background:var(--panel2);border:1px solid var(--line);border-radius:13px;padding:12px}.br-kpi small{display:block;color:var(--muted);text-transform:uppercase}.br-kpi b{display:block;font-size:26px}.br-detail{background:var(--panel2);border:1px solid var(--line);border-radius:13px;padding:12px;min-height:155px}.br-detail h3{margin:0 0 8px}.br-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.br-detail-grid div{border:1px solid var(--line);border-radius:9px;padding:7px}.br-table-card{margin-top:12px}.br-table-wrap{overflow:auto;max-height:340px}.br-table{width:100%;min-width:760px;border-collapse:collapse}.br-table th,.br-table td{padding:8px;border-bottom:1px solid var(--line);font-size:12px;text-align:left}.br-pill{display:inline-block;border-radius:999px;padding:3px 7px;font-weight:800}.br-pill.ok{color:#78e0a1}.br-pill.warn{color:#ffd15c}.br-pill.risk{color:#ff9a3d}.br-pill.crit{color:#ff7373}.br-note{color:var(--muted);font-size:11px;margin-top:8px}@media(max-width:1050px){.br-map-block{grid-template-columns:1fr}}@media(max-width:700px){.br-map-svg{height:430px}.br-map-wrap{min-height:430px}}`;document.head.appendChild(s);}
function data(){const d=typeof db!=='undefined'&&db?db:{actions:[],audits:[],kpis:[],risks:[],alerts:[],events:[]};const docs=Array.isArray(window.docItems)?window.docItems:[];const norms=Array.isArray(window.normItems)?window.normItems:[];const normAlerts=Array.isArray(window.normAlerts)?window.normAlerts:[];const now=new Date();const actions=d.actions||[],open=actions.filter(x=>String(x.status||'').toLowerCase()!=='concluída'),late=open.filter(x=>x.due&&new Date(x.due+'T23:59:59')<now);const audits=d.audits||[],kpis=d.kpis||[],risks=d.risks||[];const badKpis=kpis.filter(x=>Number.isFinite(+x.value)&&Number.isFinite(+x.target)&&+x.value<+x.target).length;const critical=risks.filter(x=>(+(x.p||0)*+(x.i||0))>=15).length;const docDue=docs.filter(x=>x.next_review_date&&new Date(x.next_review_date+'T23:59:59')<now).length;const alerts=(d.alerts||[]).length+normAlerts.length;const score=(base,bad,total)=>Math.max(0,Math.min(100,Math.round(base-(total?bad/total*45:0))));return[
{key:'DOCS',name:'Documentos',count:docs.length,bad:docDue,score:score(96,docDue,Math.max(1,docs.length)),view:'docs',sub:`${docDue} revisão(ões) vencida(s)`,x:220,y:120},
{key:'ACTIONS',name:'RQ 045 / Ações',count:open.length,bad:late.length,score:score(95,late.length,Math.max(1,open.length)),view:'actions',sub:`${late.length} atrasada(s)`,x:365,y:125},
{key:'AUDITS',name:'Auditorias',count:audits.length,bad:0,score:audits.length?88:70,view:'audits',sub:'programadas / realizadas',x:480,y:210},
{key:'KPIS',name:'Indicadores',count:kpis.length,bad:badKpis,score:score(94,badKpis,Math.max(1,kpis.length)),view:'kpis',sub:`${badKpis} fora da meta`,x:385,y:285},
{key:'RISKS',name:'Riscos',count:risks.length,bad:critical,score:score(93,critical,Math.max(1,risks.length)),view:'risks',sub:`${critical} crítico(s)`,x:265,y:255},
{key:'NORMS',name:'Normas / Portarias',count:norms.length,bad:normAlerts.length,score:score(97,normAlerts.length,Math.max(1,norms.length)),view:'norms',sub:`${normAlerts.length} alerta(s)`,x:465,y:345},
{key:'ALERTS',name:'Agenda / Alertas',count:alerts,bad:alerts,score:Math.max(45,95-alerts*3),view:'agenda',sub:'pendências do SGQ',x:355,y:385},
{key:'HISTORY',name:'Histórico',count:(d.events||[]).length,bad:0,score:90,view:'history',sub:'eventos registrados',x:300,y:455}
];}
function ensure(){const exec=$('execDashboard');if(!exec||$('brazilMapBlock'))return false;const wrap=document.createElement('div');wrap.id='brazilMapBlock';wrap.innerHTML=`<div class="br-map-block"><section class="br-map-card"><div class="br-head"><div><h2>Mapa do Brasil — Dados do SGQ Manager Online</h2><p>Visão executiva dos módulos e dados carregados no sistema.</p></div><div class="br-mode"><button class="btn active" id="brModeSgq" type="button">Dados SGQ Manager</button><button class="btn alt" id="brModeState" type="button">Por Estado</button></div></div><div class="br-map-wrap" id="brMapVisual"></div><div class="br-note">Modo principal sem dependências externas. O mapa não bloqueia o carregamento do SGQ Manager.</div></section><aside class="br-side" id="brMapSide"></aside></div><section class="br-map-card br-table-card"><div class="br-head"><div><h3 id="brTableTitle" style="margin:0">Resumo dos módulos do SGQ Manager</h3><p id="brTableSubtitle">Situação operacional consolidada do sistema.</p></div><button class="btn alt" id="brExportCsv" type="button">Exportar CSV</button></div><div id="brMapTable" class="br-table-wrap"></div></section>`;const ribbon=$('vectorRibbon');(ribbon?.parentNode||exec).insertBefore(wrap,ribbon?ribbon.nextSibling:exec.firstChild);$('brModeSgq').onclick=()=>{mode='SGQ';render()};$('brModeState').onclick=()=>{mode='STATE';render()};return true;}
function openView(v){const btn=document.querySelector(`.nav[data-view="${v}"]`);if(btn)btn.click();}
function renderSgq(){const rows=data();const avg=rows.length?Math.round(rows.reduce((a,b)=>a+b.score,0)/rows.length):0;const critical=rows.filter(x=>x.score<60).length;const pending=rows.reduce((a,b)=>a+(b.bad||0),0);$('brMapVisual').innerHTML=`<svg class="br-map-svg" viewBox="0 0 700 540" role="img" aria-label="Mapa executivo do SGQ Manager"><path class="br-outline" d="M180 45 L285 65 L355 40 L450 70 L525 135 L550 205 L520 265 L485 315 L470 370 L430 420 L390 485 L340 510 L300 470 L255 420 L220 350 L185 300 L150 240 L135 180 L155 120 Z"/>${rows.map(r=>`<g class="br-node" data-view="${r.view}" transform="translate(${r.x},${r.y})"><circle r="48" fill="rgba(7,17,31,.92)" stroke="${color(r.score)}"/><text class="n1" y="-11">${esc(r.name)}</text><text class="n2" y="13">${r.count}</text><text class="n3" y="30">Saúde ${r.score}%</text></g>`).join('')}</svg>`;$('brMapVisual').querySelectorAll('.br-node').forEach(n=>n.onclick=()=>openView(n.dataset.view));$('brMapSide').innerHTML=`<div class="br-kpi"><small>Saúde média do SGQ</small><b style="color:${color(avg)}">${avg}%</b><span>${label(avg)}</span></div><div class="br-kpi"><small>Pendências críticas</small><b>${pending}</b><span>somatório dos módulos</span></div><div class="br-kpi"><small>Módulos em risco</small><b>${critical}</b><span>abaixo de 60%</span></div><div class="br-detail"><h3>Como usar</h3><p class="muted">Clique em qualquer módulo sobre o mapa para abrir diretamente a área correspondente.</p><p class="muted">As quantidades são calculadas a partir dos dados carregados no SGQ Manager Online.</p></div>`;$('brMapTable').innerHTML=`<table class="br-table"><thead><tr><th>Módulo</th><th>Registros</th><th>Pendências</th><th>Saúde</th><th>Situação</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a href="#" data-view="${r.view}">${esc(r.name)}</a></td><td>${r.count}</td><td>${r.bad}</td><td>${r.score}%</td><td><span class="br-pill ${cls(r.score)}">${label(r.score)}</span></td></tr>`).join('')}</tbody></table>`;$('brMapTable').querySelectorAll('a[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();openView(a.dataset.view)});$('brExportCsv').onclick=()=>exportCsv(rows);}
function renderState(){$('brMapVisual').innerHTML=`<div style="padding:28px"><h3>Visão por Estado</h3><p class="muted">Este modo foi mantido como opcional. Para preservar estabilidade e velocidade, a visão geográfica detalhada por UF não é carregada automaticamente.</p><p class="muted">O modo principal agora é “Dados SGQ Manager”, conforme solicitado.</p></div>`;$('brMapSide').innerHTML=`<div class="br-detail"><h3>Modo secundário</h3><p class="muted">A visualização por estado permanece disponível como expansão futura sem interferir no carregamento do sistema.</p></div>`;$('brMapTable').innerHTML='';}
function exportCsv(rows){const head=['Modulo','Registros','Pendencias','Saude','Situacao'];const all=[head,...rows.map(r=>[r.name,r.count,r.bad,r.score,label(r.score)])];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=all.map(r=>r.map(q).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='SGQ_Manager_Resumo_Modulos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function render(){installStyle();ensure();const s=$('brModeSgq'),t=$('brModeState');if(s&&t){s.classList.toggle('active',mode==='SGQ');t.classList.toggle('active',mode==='STATE');}mode==='SGQ'?renderSgq():renderState();}
window.renderBrazilMap=render;window.SGQBrazilMap={render,setMode:m=>{mode=m==='STATE'?'STATE':'SGQ';render()},getMode:()=>mode};setTimeout(()=>{try{render()}catch(e){console.error('SGQ Brazil map',e)}},1500);
})();