(() => {
  'use strict';
  const LEGACY_IDS=['actList','audList','kpiList','riskList','alertList','agendaList','eventList','kd','ka','ku','ki','kn','kx','dashAlerts','dashDue','dashEvents'];
  const $=id=>document.getElementById(id), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const MASTER_MODULES=[['ACTIONS','RQ 045 / Ações','Criar, editar, atualizar, concluir e excluir ações.'],['AUDITS','Auditorias','Planejar, registrar resultados, editar e encerrar auditorias.'],['KPIS','Indicadores','Cadastrar indicadores, metas, valores, análises e histórico.'],['RISKS','Riscos e oportunidades','Cadastrar, avaliar, tratar, monitorar e encerrar riscos.'],['ALERTS','Agenda e alertas','Criar e administrar alertas, agenda e prioridades.'],['NORMS','Normas e Portarias','Cadastrar, atualizar e monitorar requisitos normativos.'],['HISTORY','Histórico de Revisões','Criar nova revisão ou retificação preservando rastreabilidade.'],['DOCS','Documentos','Editar cadastro documental completo e controlar revisões.'],['USERS','Usuários e acessos','Administrar usuários, papéis, status e credenciais.']];
  function ensureLegacyTargets(){let box=$('sgqLegacyCompatTargets');if(!box){box=document.createElement('div');box.id='sgqLegacyCompatTargets';box.hidden=true;box.setAttribute('aria-hidden','true');document.body.appendChild(box);}for(const id of LEGACY_IDS){if(!$(id)){const el=document.createElement('div');el.id=id;box.appendChild(el);}}}
  function loadMasterAdmin(){if(window.__sgqMasterLoaded||document.querySelector('script[data-sgq-master]'))return;const s=document.createElement('script');s.src='master-admin.js?v=20260831-r2';s.dataset.sgqMaster='1';s.onload=()=>{window.__sgqMasterLoaded=true;setTimeout(()=>{reconcileMaster();reconcileMasterUx();},300)};document.body.appendChild(s);}
  function hideAll(){qa('.view').forEach(v=>v.classList.add('hidden'));const p=$('masterAdminPanel');if(p)p.classList.add('hidden');}
  function showDash(){hideAll();$('dash')?.classList.remove('hidden');qa('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view==='dash'));}
  function masterCss(){if($('masterUxStyle'))return;const s=document.createElement('style');s.id='masterUxStyle';s.textContent=`#masterAdminPanel{padding:0!important;background:transparent!important;border:0!important}.master-home{display:grid;gap:12px}.master-home-head{border:1px solid #285b89;background:linear-gradient(135deg,rgba(22,134,255,.16),rgba(84,179,255,.04));border-radius:16px;padding:18px}.master-home-head h2{margin:0 0 4px;font-size:24px}.master-home-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.master-home-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.master-home-card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:14px;text-align:left;color:var(--text);cursor:pointer;min-height:118px}.master-home-card:hover{border-color:#54b3ff;transform:translateY(-1px)}.master-home-card b{display:block;font-size:16px;margin-bottom:6px}.master-home-card small{color:var(--muted);line-height:1.35}.master-working{display:none}.master-working.active{display:block}.master-back{margin-bottom:10px}.masterform textarea{min-height:82px}.masterlist{min-height:170px}@media(max-width:1000px){.master-home-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.master-home-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function nativeClick(view){const b=qa('.nav').find(n=>n.dataset.view===view);if(b)b.click();}
  function showMasterHome(){reconcileMasterUx();$('masterHome')?.classList.remove('hidden');$('masterWorking')?.classList.remove('active');window.scrollTo({top:0,behavior:'smooth'});}
  function showMasterWork(){reconcileMasterUx();$('masterHome')?.classList.add('hidden');$('masterWorking')?.classList.add('active');}
  function openMasterModule(key){if(key==='DOCS'){nativeClick('docs');return}if(key==='USERS'){nativeClick('users');return}const tab=qa('[data-master-tab]').find(x=>x.dataset.masterTab===key);if(tab){showMasterWork();tab.click();}}
  function reconcileMasterUx(){const p=$('masterAdminPanel');if(!p)return;masterCss();if(!$('masterHome')){const bar=p.querySelector('.masterbar'),grid=p.querySelector('.mastergrid'),tools=p.querySelector('.mastertools'),hint=p.querySelector('.masterhint');if(!bar||!grid)return;const work=document.createElement('div');work.id='masterWorking';work.className='master-working';grid.parentNode.insertBefore(work,grid);work.appendChild(bar);work.appendChild(grid);if(tools)work.appendChild(tools);if(hint)work.appendChild(hint);const back=document.createElement('div');back.className='master-back';back.innerHTML='<button class="btn alt" id="masterBackHome" type="button">← Visão geral MASTER</button>';work.prepend(back);const home=document.createElement('div');home.id='masterHome';home.className='master-home';home.innerHTML=`<div class="master-home-head"><div class="toolbar" style="justify-content:space-between;align-items:flex-start"><div><h2>Administração MASTER</h2><div class="muted">Central de edição completa do SGQ Manager. Selecione o módulo que deseja administrar.</div></div><span class="tag ok">MASTER · EDIÇÃO 100%</span></div><div class="master-home-actions"><button class="btn" id="masterGoDash">Voltar ao Dashboard Executivo</button><button class="btn alt" id="masterGoDocs">Documentos</button><button class="btn alt" id="masterGoUsers">Usuários e acessos</button></div></div><div class="master-home-grid">${MASTER_MODULES.map(([k,l,d])=>`<button class="master-home-card" type="button" data-master-home="${k}"><b>${l}</b><small>${d}</small></button>`).join('')}</div>`;p.prepend(home);qa('[data-master-home]',home).forEach(b=>b.onclick=()=>openMasterModule(b.dataset.masterHome));$('masterGoDash').onclick=()=>nativeClick('dash');$('masterGoDocs').onclick=()=>nativeClick('docs');$('masterGoUsers').onclick=()=>nativeClick('users');$('masterBackHome').onclick=showMasterHome;}qa('[data-master-tab]').forEach(t=>{if(t.dataset.masterUxBound)return;t.dataset.masterUxBound='1';t.addEventListener('click',showMasterWork);});}
  function reconcileMaster(){const p=$('masterAdminPanel'),side=document.querySelector('.side');if(!p||!side)return;p.classList.add('view','hidden');p.dataset.view='master-admin';let b=$('masterAdminNav');if(!b){b=document.createElement('button');b.id='masterAdminNav';b.className='nav hidden';b.dataset.view='master-admin';b.textContent='09 · Administração MASTER — Edição completa';const users=$('usersNav');side.insertBefore(b,users||side.querySelector('hr'));}const isMaster=($('sessionBadge')?.textContent||'').includes('MASTER');b.classList.toggle('hidden',!isMaster);const users=$('usersNav');if(users)users.textContent='10 · Usuários e acessos — MASTER';const hist=qa('.nav').find(n=>n.dataset.view==='history');if(hist)hist.textContent='11 · Histórico de Revisões';b.onclick=()=>{hideAll();p.classList.remove('hidden');qa('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');showMasterHome();};reconcileMasterUx();}
  function turnstileSvg(){return `<svg viewBox="0 0 360 210" role="img" aria-label="Controle de Fluxo"><defs><linearGradient id="tsg2" x1="0" x2="1"><stop stop-color="#2b3038"/><stop offset="1" stop-color="#090c10"/></linearGradient></defs><rect x="63" y="30" width="76" height="154" rx="15" fill="url(#tsg2)" stroke="#3f4853"/><rect x="76" y="15" width="68" height="43" rx="10" fill="#242a31" stroke="#3f4853"/><path d="M74 48h55" stroke="#28a9ff" stroke-width="5" stroke-linecap="round"/><rect x="105" y="23" width="25" height="16" rx="3" fill="#373e47"/><circle cx="139" cy="106" r="16" fill="#11161c" stroke="#cdd5dc" stroke-width="2"/><path d="M139 106l100-27M139 106l79 70M139 106l-35 91" stroke="#dfe7ee" stroke-width="10" stroke-linecap="round"/><path d="M139 106l100-27M139 106l79 70M139 106l-35 91" stroke="#7f8b96" stroke-width="2" stroke-linecap="round"/></svg>`;}
  function liftSvg(){return `<svg viewBox="0 0 360 210" role="img" aria-label="Mobilidade"><defs><linearGradient id="lyg2" x1="0" x2="1"><stop stop-color="#fff400"/><stop offset="1" stop-color="#d1b700"/></linearGradient></defs><rect x="74" y="25" width="30" height="157" rx="4" fill="#171a1f"/><rect x="254" y="25" width="30" height="157" rx="4" fill="#171a1f"/><path d="M88 19v126M270 19v126" stroke="url(#lyg2)" stroke-width="11"/><path d="M91 147h180v34H91z" fill="#181b20" stroke="#ffe700" stroke-width="7"/><path d="M112 143h138V88H112z" fill="none" stroke="#ffe700" stroke-width="7"/><path d="M112 88l20 55M250 88l-20 55" stroke="#ffe700" stroke-width="7"/><rect x="250" y="62" width="58" height="75" rx="5" fill="#24282e"/><circle cx="278" cy="79" r="5" fill="#20c96b"/><circle cx="278" cy="98" r="5" fill="#ffcc33"/><circle cx="278" cy="117" r="5" fill="#ff4d4d"/></svg>`;}
  function reconcileDashboard(){const dash=$('execDashboard');if(!dash)return;const boxes=qa('.machine-box',dash);if(boxes[0]){const h=boxes[0].querySelector('h4');if(h)h.textContent='Controle de Fluxo';const p=boxes[0].querySelector('p');if(p)p.textContent='Catraca como vetor de controle de fluxo, liberação, segurança e rastreabilidade.';const s=boxes[0].querySelector('svg');if(s)s.outerHTML=turnstileSvg();const st=boxes[0].querySelector('.machine-status');if(st)st.textContent='CONTROLE DE FLUXO';}if(boxes[1]){const h=boxes[1].querySelector('h4');if(h)h.textContent='Mobilidade';const p=boxes[1].querySelector('p');if(p)p.textContent='Plataforma elevatória como vetor de mobilidade, acessibilidade, segurança e conformidade.';const s=boxes[1].querySelector('svg');if(s)s.outerHTML=liftSvg();const st=boxes[1].querySelector('.machine-status');if(st)st.textContent='MOBILIDADE';}const sub=dash.querySelector('.exec-sub');if(sub)sub.textContent='Visão executiva do SGQ com Controle de Fluxo, Mobilidade, Velocímetro de Conformidade, indicadores, alertas e histórico.';}
  function bindNav(){qa('.nav').forEach(b=>{if(b.dataset.compatBound)return;b.dataset.compatBound='1';b.addEventListener('click',()=>{if(b.dataset.view!=='master-admin')$('masterAdminPanel')?.classList.add('hidden');});});}
  function install(){ensureLegacyTargets();loadMasterAdmin();setTimeout(()=>{showDash();reconcileMaster();reconcileMasterUx();reconcileDashboard();bindNav();},1400);setInterval(()=>{reconcileMaster();reconcileMasterUx();reconcileDashboard();bindNav();},1800);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();