(() => {
'use strict';
const $=id=>document.getElementById(id);
const API='sgq-master-admin';
const state={module:'ACTIONS',editing:null,items:[],audit:[]};
const MODS={
 ACTIONS:{label:'RQ 045 / Ações',fields:[['code','Código'],['title','Título *'],['description','Descrição','textarea'],['action_plan','Plano de ação','textarea'],['owner','Responsável'],['priority','Prioridade','select','low|medium|high|critical'],['due_date','Prazo','date'],['status','Status','select','open|in_progress|awaiting_validation|completed|verified|closed|overdue|cancelled'],['effectiveness_status','Eficácia'],['effectiveness_notes','Notas de eficácia','textarea']]},
 AUDITS:{label:'Auditorias',fields:[['code','Código'],['title','Título *'],['audit_type','Tipo','select','INTERNAL|SUPPLIER|5S|CERTIFICATION|PROCESS|PRODUCT'],['scope','Escopo','textarea'],['standard_reference','Norma / referência'],['planned_date','Data planejada','date'],['status','Status','select','PLANNED|IN_PROGRESS|COMPLETED|CANCELLED'],['result','Resultado','textarea'],['audit_origin','Origem']]},
 KPIS:{label:'Indicadores',fields:[['code','Código'],['name','Indicador *'],['unit','Unidade'],['direction','Direção','select','higher_better|lower_better|target'],['target','Meta','number'],['warning_limit','Limite atenção','number'],['critical_limit','Limite crítico','number'],['frequency','Frequência','select','DAILY|WEEKLY|MONTHLY|QUARTERLY|SEMIANNUAL|ANNUAL'],['status','Status','select','ACTIVE|INACTIVE'],['reference_date','Data referência','date'],['value','Valor','number'],['analysis','Análise','textarea']]},
 RISKS:{label:'Riscos e oportunidades',fields:[['code','Código'],['title','Título *'],['description','Descrição','textarea'],['risk_type','Tipo','select','RISK|OPPORTUNITY'],['probability','Probabilidade 1–5','number'],['impact','Impacto 1–5','number'],['treatment','Tratamento','textarea'],['due_date','Prazo','date'],['status','Status','select','OPEN|TREATING|MONITORING|CLOSED']]},
 ALERTS:{label:'Agenda e alertas',fields:[['title','Título *'],['message','Mensagem','textarea'],['type','Tipo'],['source_module','Módulo origem'],['priority','Prioridade','select','low|medium|high|critical'],['record_id','Registro relacionado']]},
 NORMS:{label:'Normas e Portarias',fields:[['normative_type','Tipo'],['issuer','Emissor'],['reference','Referência *'],['title','Título *'],['source_url','URL oficial'],['status','Status','select','ACTIVE|REVOKED|SUPERSEDED|DRAFT'],['current_version','Versão atual'],['publication_date','Publicação','date'],['effective_date','Vigência','date'],['next_review_date','Próxima revisão','date'],['check_frequency','Monitoramento','select','DAILY|WEEKLY|MONTHLY'],['notes','Observações','textarea']]},
 HISTORY:{label:'Histórico de Revisões',fields:[['document_code','Código do documento *'],['revision','Revisão *'],['change_summary','Resumo / motivo da revisão *','textarea'],['approval_status','Status aprovação','select','DRAFT|UNDER_REVIEW|APPROVED|REJECTED'],['approved_at','Data aprovação','datetime-local']]}
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function invoke(body){const {data,error}=await sb.functions.invoke(API,{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data;}
function css(){if($('masterAdminStyle'))return;const s=document.createElement('style');s.id='masterAdminStyle';s.textContent=`
.masterbar{border:1px solid #285b89;background:linear-gradient(135deg,rgba(22,134,255,.14),rgba(76,201,240,.05));border-radius:14px;padding:14px;margin:0 0 14px}.masterbar h2{margin:0}.mastertabs{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.mastertab{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:7px 9px;border-radius:9px;cursor:pointer}.mastertab.active{border-color:#54b3ff;background:rgba(22,134,255,.15)}.mastergrid{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.masterform{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.masterform .wide{grid-column:1/-1}.masterlist{display:grid;gap:8px;max-height:620px;overflow:auto}.masteritem{border:1px solid var(--line);background:var(--panel2);border-radius:10px;padding:10px}.masteritem .toolbar{margin-top:8px}.mastertools{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px}.mastertool{border:1px solid var(--line);background:var(--panel2);border-radius:11px;padding:10px}.mastertool b{display:block}.mastertool small{color:var(--muted);display:block;margin:4px 0 8px}.mastertool .btn{width:100%;padding:7px 8px}.masterhint{margin-top:10px;padding:10px;border:1px dashed var(--line);border-radius:10px;color:var(--muted)}@media(max-width:1000px){.mastergrid{grid-template-columns:1fr}.mastertools{grid-template-columns:1fr 1fr}.masterform{grid-template-columns:1fr}}@media(max-width:600px){.mastertools{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function ensure(){if($('masterAdminPanel'))return;const main=document.querySelector('.main');if(!main)return;const sec=document.createElement('section');sec.id='masterAdminPanel';sec.className='card';sec.innerHTML=`<div class="masterbar"><div class="toolbar" style="justify-content:space-between"><div><h2>Administração MASTER</h2><div class="muted">Criação, edição, atualização, exclusão controlada e histórico por módulo.</div></div><span class="tag ok">MASTER · EDIÇÃO COMPLETA</span></div><div class="mastertabs" id="masterTabs"></div></div><div class="mastergrid"><div><h3 id="masterTitle"></h3><form id="masterForm" class="masterform"></form><div class="toolbar section"><button class="btn" id="masterSave" type="button">Criar registro</button><button class="btn alt hidden" id="masterCancel" type="button">Cancelar edição</button><button class="btn alt" id="masterRefresh" type="button">Atualizar</button></div><p id="masterMsg" class="muted"></p></div><div><div class="toolbar" style="justify-content:space-between"><h3 style="margin:0">Registros</h3><div class="toolbar"><button class="btn alt" id="masterExport" type="button">CSV</button><button class="btn alt" id="masterExcel" type="button">Excel</button></div></div><div class="masterlist section" id="masterList"></div></div></div><div class="mastertools"><div class="mastertool"><b>Excel / Office</b><small>Exportação XLSX para análises, tabelas, gráficos e relatórios.</small><button class="btn alt" id="toolExcel" type="button">Exportar Excel</button></div><div class="mastertool"><b>Power Query</b><small>Arquivo tabular padronizado para ETL, consolidação e atualização.</small><button class="btn alt" id="toolPQ" type="button">Gerar fonte CSV</button></div><div class="mastertool"><b>Microsoft Project</b><small>Plano de ações em formato compatível com importação de tarefas.</small><button class="btn alt" id="toolProject" type="button">Gerar cronograma CSV</button></div><div class="mastertool"><b>Canva</b><small>Comunicação visual, relatórios, apresentações e materiais do SGQ.</small><button class="btn alt" id="toolCanva" type="button">Abrir Canva</button></div><div class="mastertool"><b>IA</b><small>Classificação, resumo, análise e priorização com revisão humana.</small><button class="btn alt" id="toolAI" type="button">Analisar módulo</button></div></div><div class="masterhint" id="masterToolMsg">Recursos administrativos prontos para uso com os dados do módulo selecionado.</div>`;main.insertBefore(sec,main.firstChild);}
function renderTabs(){const e=$('masterTabs');e.innerHTML=Object.entries(MODS).map(([k,m])=>`<button type="button" class="mastertab ${state.module===k?'active':''}" data-master-tab="${k}">${m.label}</button>`).join('')+`<button type="button" class="mastertab" data-open-native="docs">Documentos</button><button type="button" class="mastertab" data-open-native="users">Usuários</button>`;}
function inputHtml(f){const [key,label,type='text',opts='']=f;const wide=type==='textarea'?' wide':'';if(type==='textarea')return `<div class="field${wide}"><label>${label}</label><textarea name="${key}"></textarea></div>`;if(type==='select')return `<div class="field"><label>${label}</label><select name="${key}">${opts.split('|').map(o=>`<option>${o}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label><input name="${key}" type="${type}" ${type==='number'?'step="any"':''}></div>`;}
function renderForm(){const m=MODS[state.module];$('masterTitle').textContent=m.label;$('masterForm').innerHTML=m.fields.map(inputHtml).join('');$('masterSave').textContent=state.editing?'Salvar alterações':'Criar registro';$('masterCancel').classList.toggle('hidden',!state.editing);}
function display(row){const title=row.title||row.name||row.reference||row.revision||row.code||row.id;const sub=row.status||row.approval_status||row.due_date||row.planned_date||row.created_at||'';return `<div class="masteritem"><b>${esc(title)}</b><div class="muted">${esc(sub)}</div>${state.module==='HISTORY'?`<div class="muted">${esc(row.document?.code||'')} · ${esc(row.change_summary||'')}</div>`:`<div class="toolbar"><button class="btn alt" data-master-edit="${row.id}">Editar</button><button class="btn danger" data-master-del="${row.id}">Excluir</button></div>`}</div>`;}
async function load(){try{$('masterMsg').textContent='Carregando...';const d=await invoke({action:'list',module:state.module});state.items=d.items||[];state.audit=d.audit||[];$('masterList').innerHTML=state.items.map(display).join('')||'<span class="muted">Nenhum registro cadastrado.</span>';$('masterMsg').textContent=state.module==='HISTORY'?`${state.items.length} revisão(ões) · ${state.audit.length} evento(s) de auditoria`:`${state.items.length} registro(s)`;}catch(e){$('masterMsg').textContent='Falha: '+(e.message||e)}}
function values(){const fd=new FormData($('masterForm'));return Object.fromEntries([...fd.entries()].filter(([,v])=>v!==''));}
function fill(row){const f=$('masterForm');Object.entries(row).forEach(([k,v])=>{const el=f.elements.namedItem(k);if(el&&v!=null&&typeof v!=='object')el.value=String(v).slice(0,16);});if(state.module==='ACTIONS'){if(f.elements.owner)f.elements.owner.value=row.metadata?.owner_name||'';}if(state.module==='KPIS'){const latest=[...(row.values||[])].sort((a,b)=>String(b.reference_date).localeCompare(String(a.reference_date)))[0];if(latest){if(f.elements.reference_date)f.elements.reference_date.value=latest.reference_date||'';if(f.elements.value)f.elements.value=latest.value??'';if(f.elements.analysis)f.elements.analysis.value=latest.analysis||'';}}}
async function save(){try{const item=values();$('masterSave').disabled=true;$('masterMsg').textContent='Salvando...';await invoke({action:state.editing?'update':'create',module:state.module,id:state.editing||undefined,item});state.editing=null;$('masterForm').reset();renderForm();await load();if(window.SGQCentralSync?.pullCentral)await window.SGQCentralSync.pullCentral();}catch(e){alert(e.message||e)}finally{$('masterSave').disabled=false;}}
async function del(id){if(!confirm('Excluir definitivamente este registro?'))return;try{await invoke({action:'delete',module:state.module,id});await load();if(window.SGQCentralSync?.pullCentral)await window.SGQCentralSync.pullCentral();}catch(e){alert(e.message||e)}}
function flatRows(rows=state.items){return rows.map(r=>{const o={};Object.entries(r).forEach(([k,v])=>{if(v==null||typeof v!=='object')o[k]=v;else if(k==='document')o.document_code=v?.code||'';else if(k==='metadata')o.metadata=JSON.stringify(v);});return o;});}
function csvRows(rows,name){if(!rows.length)return;const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))],q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const out=[keys.map(q).join(';'),...rows.map(r=>keys.map(k=>q(r[k])).join(';'))].join('\n');const b=new Blob(['\ufeff'+out],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function csv(){csvRows(flatRows(),`SGQ_${state.module}_${new Date().toISOString().slice(0,10)}.csv`);}
function excel(){const rows=flatRows();if(!rows.length)return;if(!window.XLSX)return csv();const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,state.module.slice(0,31));XLSX.writeFile(wb,`SGQ_${state.module}_${new Date().toISOString().slice(0,10)}.xlsx`);}
function projectCsv(){const rows=(state.module==='ACTIONS'?state.items:[]).map((r,i)=>({ID:i+1,'Task Name':r.title||'',Notes:r.description||'',Resource:r.metadata?.owner_name||'',Start:r.created_at?String(r.created_at).slice(0,10):'',Finish:r.due_date||'',Status:r.status||'',Priority:r.priority||''}));if(!rows.length){$('masterToolMsg').textContent='Microsoft Project: selecione RQ 045 / Ações para gerar o cronograma.';return;}csvRows(rows,`SGQ_Project_Acoes_${new Date().toISOString().slice(0,10)}.csv`);$('masterToolMsg').textContent='Cronograma CSV gerado para importação no Microsoft Project.';}
function powerQuery(){const rows=flatRows();if(!rows.length)return;csvRows(rows,`SGQ_PowerQuery_${state.module}_${new Date().toISOString().slice(0,10)}.csv`);$('masterToolMsg').textContent='Fonte tabular gerada para Excel/Power Query. Use Obter Dados > Texto/CSV.';}
function canva(){window.open('https://www.canva.com/','_blank','noopener');$('masterToolMsg').textContent='Canva aberto em nova aba. A integração direta com dados do SGQ exige conexão/autorização específica.';}
function aiSummary(){const n=state.items.length;let crit=0;if(state.module==='ACTIONS')crit=state.items.filter(x=>['critical','overdue'].includes(String(x.priority||x.status||'').toLowerCase())).length;if(state.module==='RISKS')crit=state.items.filter(x=>Number(x.score||0)>=15).length;if(state.module==='KPIS')crit=state.items.filter(x=>{const v=[...(x.values||[])].sort((a,b)=>String(b.reference_date).localeCompare(String(a.reference_date)))[0]?.value;return Number.isFinite(+v)&&Number.isFinite(+x.target)&&+v<+x.target}).length;const msg=`IA assistiva · ${MODS[state.module].label}: ${n} registro(s) analisado(s) nesta visão${crit?` · ${crit} item(ns) requerem atenção prioritária`:''}. A decisão final permanece com o responsável humano.`;$('masterToolMsg').textContent=msg;}
function native(view){document.querySelector(`.nav[data-view="${view}"]`)?.click();}
async function install(){css();ensure();renderTabs();renderForm();document.addEventListener('click',async e=>{const t=e.target.closest('[data-master-tab]');if(t){state.module=t.dataset.masterTab;state.editing=null;renderTabs();renderForm();await load();return;}const n=e.target.closest('[data-open-native]');if(n){native(n.dataset.openNative);return;}const ed=e.target.closest('[data-master-edit]');if(ed){const row=state.items.find(x=>String(x.id)===String(ed.dataset.masterEdit));if(row){state.editing=row.id;renderForm();fill(row);$('masterForm').scrollIntoView({behavior:'smooth'});}return;}const d=e.target.closest('[data-master-del]');if(d)await del(d.dataset.masterDel);});$('masterSave').onclick=save;$('masterCancel').onclick=()=>{state.editing=null;$('masterForm').reset();renderForm();};$('masterRefresh').onclick=load;$('masterExport').onclick=csv;$('masterExcel').onclick=excel;$('toolExcel').onclick=excel;$('toolPQ').onclick=powerQuery;$('toolProject').onclick=projectCsv;$('toolCanva').onclick=canva;$('toolAI').onclick=aiSummary;try{const c=await invoke({action:'context'});if(c.role!=='MASTER'){$('masterAdminPanel').classList.add('hidden');return;}await load();}catch(e){$('masterAdminPanel').classList.add('hidden');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,900));else setTimeout(install,900);
window.SGQMasterAdmin={load,excel,powerQuery,projectCsv};
})();