(() => {
'use strict';
const $=id=>document.getElementById(id);
const state={tab:'word',sheet:[['Campo','Valor'],['Exemplo','']],project:[],query:[]};
function css(){if($('prodStyle'))return;const s=document.createElement('style');s.id='prodStyle';s.textContent=`
.prod{margin:0 0 14px}.prodTabs{display:flex;gap:7px;flex-wrap:wrap}.prodTab{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:8px 10px;border-radius:9px;cursor:pointer}.prodTab.active{border-color:#54b3ff;background:rgba(22,134,255,.15)}.prodPane{margin-top:12px}.prodToolbar{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px}.prodEditor{min-height:260px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);padding:14px;outline:none}.prodGrid{overflow:auto;border:1px solid var(--line);border-radius:10px}.prodGrid table{border-collapse:collapse;width:100%;min-width:700px}.prodGrid th,.prodGrid td{border:1px solid var(--line);padding:7px}.prodGrid td{background:var(--panel2)}.prodGrid input{border:0;background:transparent;padding:4px}.prodSlides{display:grid;grid-template-columns:240px 1fr;gap:10px}.prodSlideList{display:grid;gap:7px}.prodSlide{border:1px solid var(--line);border-radius:9px;padding:8px;background:var(--panel2);cursor:pointer}.prodCanvas{min-height:320px;border:1px solid var(--line);border-radius:12px;padding:20px;background:var(--panel2)}.prodProject{overflow:auto}.prodProject table{width:100%;border-collapse:collapse}.prodProject th,.prodProject td{border-bottom:1px solid var(--line);padding:7px;text-align:left}.prodCards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.prodCard{border:1px solid var(--line);border-radius:11px;padding:12px;background:var(--panel2)}@media(max-width:900px){.prodSlides,.prodCards{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function ensure(){if($('productivityStudio'))return;const main=document.querySelector('.main');if(!main)return;const sec=document.createElement('section');sec.id='productivityStudio';sec.className='card prod';sec.innerHTML=`<div class="toolbar" style="justify-content:space-between"><div><h2 style="margin:0">Central de Produtividade e Desenvolvimento</h2><div class="muted">Edição integrada · Office · Project · Power Query · Canva · IA</div></div><span class="tag ok">MASTER</span></div><div id="prodTabs" class="prodTabs section"></div><div id="prodPane" class="prodPane"></div>`;main.insertBefore(sec,main.firstChild);}
const tabs=[['word','Word / Documentos'],['excel','Excel / Planilhas'],['powerpoint','PowerPoint'],['project','Project'],['powerquery','Power Query'],['canva','Canva'],['ai','Central de IA']];
function tabsUi(){const e=$('prodTabs');e.innerHTML=tabs.map(([k,l])=>`<button class="prodTab ${state.tab===k?'active':''}" data-prod-tab="${k}">${l}</button>`).join('');}
function dl(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function word(){return `<div class="prodToolbar"><button class="btn alt" data-cmd="bold"><b>B</b></button><button class="btn alt" data-cmd="italic"><i>I</i></button><button class="btn alt" data-cmd="underline"><u>U</u></button><button class="btn alt" data-cmd="insertUnorderedList">Lista</button><button class="btn alt" data-cmd="justifyLeft">Esq.</button><button class="btn alt" data-cmd="justifyCenter">Centro</button><button class="btn alt" data-cmd="justifyRight">Dir.</button><button class="btn alt" id="prodWordH1">Título</button><button class="btn alt" id="prodWordLink">Link</button><button class="btn" id="prodWordSave">Exportar Word</button></div><div id="prodEditor" class="prodEditor" contenteditable="true"><h2>Novo documento SGQ</h2><p>Digite e formate o conteúdo aqui.</p></div>`}
function sheetTable(){return `<div class="prodToolbar"><button class="btn alt" id="prodAddRow">+ Linha</button><button class="btn alt" id="prodAddCol">+ Coluna</button><button class="btn alt" id="prodImportCsv">Importar CSV</button><button class="btn" id="prodXlsx">Exportar XLSX</button></div><input id="prodCsvFile" type="file" accept=".csv,.xlsx,.xls" hidden><div class="prodGrid"><table><tbody>${state.sheet.map((r,i)=>`<tr>${r.map((v,j)=>`<td><input data-cell="${i}:${j}" value="${String(v??'').replaceAll('"','&quot;')}"></td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function powerpoint(){return `<div class="prodToolbar"><button class="btn alt" id="prodAddSlide">+ Slide</button><button class="btn alt" id="prodDupSlide">Duplicar</button><button class="btn" id="prodPptExport">Exportar roteiro PPT</button></div><div class="prodSlides"><div class="prodSlideList" id="prodSlideList"><div class="prodSlide active">Slide 1</div></div><div class="prodCanvas"><input id="prodSlideTitle" placeholder="Título do slide" value="Apresentação SGQ"><textarea id="prodSlideBody" rows="10" style="margin-top:8px" placeholder="Conteúdo do slide"></textarea></div></div>`}
function project(){return `<div class="prodToolbar"><button class="btn alt" id="projAdd">+ Tarefa</button><button class="btn" id="projExport">Exportar Project CSV</button></div><div class="prodProject"><table><thead><tr><th>WBS</th><th>Tarefa</th><th>Início</th><th>Fim</th><th>Responsável</th><th>%</th><th>Predecessora</th></tr></thead><tbody id="projBody"></tbody></table></div>`}
function powerquery(){return `<div class="prodCards"><div class="prodCard"><b>Fonte</b><p class="muted">Carregue CSV/XLSX e transforme antes de usar no SGQ.</p><input id="pqFile" type="file" accept=".csv,.xlsx,.xls"></div><div class="prodCard"><b>Transformações</b><div class="field"><select id="pqAction"><option value="trim">Remover espaços</option><option value="upper">Maiúsculas</option><option value="lower">Minúsculas</option><option value="dedupe">Remover duplicados</option><option value="empty">Remover linhas vazias</option></select></div><button class="btn alt" id="pqApply">Aplicar</button></div><div class="prodCard"><b>Saída</b><p id="pqInfo" class="muted">Nenhuma fonte carregada.</p><button class="btn" id="pqExport">Exportar CSV tratado</button></div></div><div id="pqPreview" class="prodGrid section"></div>`}
function canva(){return `<div class="prodCards"><div class="prodCard"><b>Canva</b><p class="muted">Crie e edite materiais visuais, relatórios, apresentações e comunicação do SGQ.</p><button class="btn" id="canvaOpen">Abrir Canva</button></div><div class="prodCard"><b>Preparar dados</b><p class="muted">Exporte dados do SGQ em XLSX/CSV e use em designs e relatórios.</p><button class="btn alt" id="canvaData">Exportar dados SGQ</button></div><div class="prodCard"><b>Integração</b><p class="muted">A edição avançada no Canva utiliza a conexão autorizada do Canva; não replicamos funções proprietárias dentro do navegador.</p></div></div>`}
function ai(){return `<div class="prodCards"><div class="prodCard"><b>Assistente SGQ</b><textarea id="aiInput" rows="7" placeholder="Cole texto, evidência, ação, auditoria ou problema..."></textarea><button class="btn section" id="aiAnalyze">Analisar</button></div><div class="prodCard"><b>Ações de IA</b><div class="list"><button class="btn alt" data-ai="summary">Resumir</button><button class="btn alt" data-ai="risk">Analisar riscos</button><button class="btn alt" data-ai="5w2h">Gerar 5W2H</button><button class="btn alt" data-ai="8d">Estruturar 8D</button><button class="btn alt" data-ai="audit">Preparar auditoria</button><button class="btn alt" data-ai="rewrite">Reescrever PT-BR</button></div></div><div class="prodCard"><b>Resultado</b><div id="aiOutput" class="muted">Aguardando análise.</div><p class="muted">Quando um provedor de IA seguro estiver conectado ao backend, estas ações poderão usar modelos externos. Até lá, a interface mantém revisão humana obrigatória.</p></div></div>`}
function render(){tabsUi();const p=$('prodPane');p.innerHTML=state.tab==='word'?word():state.tab==='excel'?sheetTable():state.tab==='powerpoint'?powerpoint():state.tab==='project'?project():state.tab==='powerquery'?powerquery():state.tab==='canva'?canva():ai();bindPane();}
function bindPane(){document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.cmd,false,null));if($('prodWordH1'))$('prodWordH1').onclick=()=>document.execCommand('formatBlock',false,'h1');if($('prodWordLink'))$('prodWordLink').onclick=()=>{const u=prompt('URL:');if(u)document.execCommand('createLink',false,u)};if($('prodWordSave'))$('prodWordSave').onclick=()=>dl('Documento_SGQ.doc',`<html><meta charset="utf-8"><body>${$('prodEditor').innerHTML}</body></html>`,'application/msword');
if($('prodAddRow'))$('prodAddRow').onclick=()=>{state.sheet.push(Array(state.sheet[0]?.length||2).fill(''));render()};if($('prodAddCol'))$('prodAddCol').onclick=()=>{state.sheet.forEach(r=>r.push(''));render()};document.querySelectorAll('[data-cell]').forEach(i=>i.oninput=()=>{const [r,c]=i.dataset.cell.split(':').map(Number);state.sheet[r][c]=i.value});if($('prodXlsx'))$('prodXlsx').onclick=()=>{if(!window.XLSX)return;const ws=XLSX.utils.aoa_to_sheet(state.sheet),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Planilha');XLSX.writeFile(wb,'Planilha_SGQ.xlsx')};if($('prodImportCsv'))$('prodImportCsv').onclick=()=>$('prodCsvFile').click();if($('prodCsvFile'))$('prodCsvFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});state.sheet=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});render()};
if($('prodPptExport'))$('prodPptExport').onclick=()=>dl('Roteiro_PowerPoint_SGQ.txt',`${$('prodSlideTitle').value}\n\n${$('prodSlideBody').value}`);if($('prodAddSlide'))$('prodAddSlide').onclick=()=>alert('Estrutura de slides pronta para evolução; o conteúdo atual pode ser exportado como roteiro ou enviado ao Canva/PowerPoint.');
if($('projAdd')){$('projAdd').onclick=()=>{state.project.push({wbs:String(state.project.length+1),task:'Nova tarefa',start:'',finish:'',owner:'',pct:0,pred:''});render()};const body=$('projBody');body.innerHTML=state.project.map((x,i)=>`<tr>${['wbs','task','start','finish','owner','pct','pred'].map(k=>`<td><input data-proj="${i}:${k}" value="${x[k]??''}"></td>`).join('')}</tr>`).join('');document.querySelectorAll('[data-proj]').forEach(el=>el.oninput=()=>{const [i,k]=el.dataset.proj.split(':');state.project[+i][k]=el.value});$('projExport').onclick=()=>{const rows=[['WBS','Nome da Tarefa','Início','Fim','Responsável','% Concluído','Predecessora'],...state.project.map(x=>[x.wbs,x.task,x.start,x.finish,x.owner,x.pct,x.pred])];dl('Projeto_SGQ.csv','\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8')}}
if($('pqFile'))$('pqFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});state.query=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});pqRender()};if($('pqApply'))$('pqApply').onclick=()=>{const a=$('pqAction').value;if(a==='trim')state.query=state.query.map(r=>r.map(v=>typeof v==='string'?v.trim():v));if(a==='upper')state.query=state.query.map(r=>r.map(v=>typeof v==='string'?v.toUpperCase():v));if(a==='lower')state.query=state.query.map(r=>r.map(v=>typeof v==='string'?v.toLowerCase():v));if(a==='empty')state.query=state.query.filter(r=>r.some(v=>String(v).trim()!==''));if(a==='dedupe'){const seen=new Set();state.query=state.query.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true})}pqRender()};if($('pqExport'))$('pqExport').onclick=()=>dl('PowerQuery_SGQ.csv','\ufeff'+state.query.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8');
if($('canvaOpen'))$('canvaOpen').onclick=()=>window.open('https://www.canva.com/','_blank','noopener');if($('canvaData'))$('canvaData').onclick=()=>{const rows=[['Módulo','Quantidade'],['Documentos',window.docItems?.length||0],['Ações',window.db?.actions?.length||0],['Auditorias',window.db?.audits?.length||0],['Indicadores',window.db?.kpis?.length||0],['Riscos',window.db?.risks?.length||0]];const ws=XLSX.utils.aoa_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'SGQ');XLSX.writeFile(wb,'Dados_SGQ_Canva.xlsx')};
document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>localAi(b.dataset.ai));if($('aiAnalyze'))$('aiAnalyze').onclick=()=>localAi('summary');}
function pqRender(){if(!$('pqInfo'))return;$('pqInfo').textContent=`${state.query.length} linha(s)`;$('pqPreview').innerHTML=state.query.length?`<table><tbody>${state.query.slice(0,20).map(r=>`<tr>${r.map(v=>`<td>${String(v??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="muted">Sem dados.</div>'}
function localAi(mode){const t=$('aiInput')?.value?.trim()||'';if(!t)return;$('aiOutput').textContent=mode==='risk'?`Análise preliminar: identifique severidade, probabilidade, controles atuais, evidências e ações antes da decisão final.`:mode==='5w2h'?`5W2H: O quê? Por quê? Onde? Quando? Quem? Como? Quanto? Preencha com base no conteúdo informado.`:mode==='8d'?`8D: D1 equipe · D2 problema · D3 contenção · D4 causa raiz · D5 corretivas · D6 implementação · D7 prevenção · D8 encerramento.`:mode==='audit'?`Auditoria: critério, escopo, evidências, amostragem, constatações, NC/OBS, responsáveis e prazos.`:mode==='rewrite'?`Texto recebido pronto para revisão em PT-BR. Conecte um provedor de IA seguro para reescrita automática completa.`:`Resumo assistivo local: ${t.slice(0,450)}${t.length>450?'…':''}`;}
function install(){css();ensure();tabsUi();render();document.addEventListener('click',e=>{const t=e.target.closest('[data-prod-tab]');if(t){state.tab=t.dataset.prodTab;render();}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,1200));else setTimeout(install,1200);
window.SGQProductivityStudio={render};
})();
