const U='https://jldmisisyqewmzqhcdob.supabase.co',K='sb_publishable__FKm_nNVYKJPRTlg-l84Kw_O9Izh8eI';
const sb=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let ctx=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fd=v=>{if(!v)return'—';let d=new Date(v.length===10?v+'T12:00:00':v);return isNaN(d)?v:d.toLocaleDateString('pt-BR')};
const it=(a,b)=>`<div class="item"><b>${esc(a)}</b><span class="meta">${esc(b)}</span></div>`;
async function cnt(t,fs=[]){let q=sb.from(t).select('*',{count:'exact',head:true});for(const [m,c,v]of fs)q=q[m](c,v);let r=await q;return r.error?null:r.count}
async function context(u){let {data:m,error}=await sb.from('user_memberships').select('tenant_id,company_id,role_id,status,is_default').eq('user_id',u.id).in('status',['ACTIVE','ATIVO']).order('is_default',{ascending:false}).limit(1).maybeSingle();if(error||!m)throw Error('Usuário autenticado, mas sem vínculo ativo com o tenant.');let [{data:r},{data:t},{data:c}]=await Promise.all([sb.from('roles').select('code,name').eq('id',m.role_id).maybeSingle(),sb.from('tenants').select('code,name').eq('id',m.tenant_id).maybeSingle(),m.company_id?sb.from('companies').select('code,trade_name,legal_name').eq('id',m.company_id).maybeSingle():Promise.resolve({data:null})]);return{user:u,m,r,t,c}}
async function load(){let x=ctx.m.tenant_id;$('contextInfo').innerHTML=`<b>${esc(ctx.user.email)}</b><br>Tenant: ${esc(ctx.t?.name||ctx.t?.code||x)}<br>Empresa: ${esc(ctx.c?.trade_name||ctx.c?.legal_name||'Escopo do tenant')}<br>Papel: <b>${esc(ctx.r?.code||'—')}</b>`;$('userBadge').textContent=`${ctx.r?.code||'USUÁRIO'} · ${ctx.user.email}`;
let [{data:mods},a,al,ag,dc,au]=await Promise.all([sb.from('sgq_modules').select('code,name,module_group,status,automation_enabled').eq('tenant_id',x).eq('is_active',true).order('sync_priority'),cnt('rq045_actions',[['eq','tenant_id',x],['not','status','in','(closed,cancelled,verified)']]),cnt('sgq_alerts',[['eq','tenant_id',x],['eq','status','OPEN']]),cnt('sgq_calendar_items',[['eq','tenant_id',x],['not','status','in','(DONE,CANCELLED)']]),cnt('sgq_documents',[['eq','tenant_id',x]]),cnt('sgq_audits',[['eq','tenant_id',x]])]);
[['kModules',mods?.length??0],['kActions',a],['kAlerts',al],['kAgenda',ag],['kDocs',dc],['kAudits',au]].forEach(([i,n])=>$(i).textContent=n??'—');$('modulesGrid').innerHTML=mods?.length?mods.map(m=>`<div class="module"><h3>${esc(m.name)}</h3><p>${esc(m.code)} · ${esc(m.module_group||'SGQ')}</p><span class="tag ${m.automation_enabled?'ok':''}">${m.automation_enabled?'AUTOMATIZADO':esc(m.status)}</span></div>`).join(''):'<div class="empty">Nenhum módulo visível.</div>';
let [{data:as},{data:als},{data:gs}]=await Promise.all([sb.from('rq045_actions').select('code,title,status,priority,due_date').eq('tenant_id',x).order('created_at',{ascending:false}).limit(8),sb.from('sgq_alerts').select('title,severity,module_code,due_at').eq('tenant_id',x).eq('status','OPEN').order('created_at',{ascending:false}).limit(8),sb.from('sgq_calendar_items').select('title,module_code,due_at,status').eq('tenant_id',x).order('due_at',{ascending:true}).limit(8)]);$('actionsList').innerHTML=as?.length?as.map(v=>it(`${v.code} — ${v.title}`,`${v.status} · ${v.priority} · prazo ${fd(v.due_date)}`)).join(''):'<div class="empty">Sem ações visíveis.</div>';$('alertsList').innerHTML=als?.length?als.map(v=>it(v.title,`${v.module_code} · ${v.severity} · ${fd(v.due_at)}`)).join(''):'<div class="empty">Sem alertas.</div>';$('agendaList').innerHTML=gs?.length?gs.map(v=>it(v.title,`${v.module_code} · ${fd(v.due_at)} · ${v.status}`)).join(''):'<div class="empty">Sem itens de agenda.</div>'}
async function enter(s){try{ctx=await context(s.user);$('loginPanel').classList.add('hidden');$('appPanel').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('gateText').textContent='Sessão autenticada; dados filtrados por RLS/RBAC.';$('gateTag').textContent='PILOTO CONECTADO';$('gateTag').className='tag ok';await load()}catch(e){$('loginMsg').textContent=e.message}}
async function leave(){ctx=null;$('loginPanel').classList.remove('hidden');$('appPanel').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('userBadge').textContent='Não autenticado'}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Autenticando...';let {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return $('loginMsg').textContent='Acesso não autorizado: '+error.message;await enter(data.session)});$('logoutBtn').onclick=async()=>{await sb.auth.signOut();await leave()};
$('actionForm').addEventListener('submit',async e=>{e.preventDefault();if(!ctx)return;let m=ctx.m;if(!m.company_id)return $('actionMsg').textContent='Vínculo sem empresa definida.';let code='RQ045-'+new Date().toISOString().replace(/\D/g,'').slice(0,14),p={tenant_id:m.tenant_id,company_id:m.company_id,code,origin:'SGQ_MANAGER',action_type:$('aType').value,title:$('aTitle').value.trim(),description:$('aDescription').value.trim(),owner_user_id:ctx.user.id,priority:$('aPriority').value,due_date:$('aDue').value,status:'open',evidence:{},metadata:{source:'SGQ_MANAGER_WEB'},created_by:ctx.user.id};$('actionMsg').textContent='Gravando...';let {error}=await sb.from('rq045_actions').insert(p);if(error)return $('actionMsg').textContent='Não gravado: '+error.message;$('actionMsg').textContent='Ação criada: '+code;e.target.reset();await load()});
(async()=>{let {data:{session}}=await sb.auth.getSession();session?await enter(session):await leave()})();