const U='https://jldmisisyqewmzqhcdob.supabase.co',K='sb_publishable__FKm_nNVYKJPRTlg-l84Kw_O9Izh8eI';
const sb=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let ctx=null,modsCache=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fd=v=>{if(!v)return'—';let d=new Date(v.length===10?v+'T12:00:00':v);return isNaN(d)?v:d.toLocaleDateString('pt-BR')};
const it=(a,b,c='')=>`<div class="item"><b>${esc(a)}</b><span class="meta">${esc(b)}</span>${c}</div>`;
async function cnt(t,fs=[]){let q=sb.from(t).select('*',{count:'exact',head:true});for(const f of fs){const [m,c,v,x]=f;if(m==='not')q=q.not(c,v,x);else q=q[m](c,v)}let r=await q;return r.error?null:r.count}
async function context(u){let {data:ms,error}=await sb.from('user_memberships').select('tenant_id,company_id,role_id,status,is_default').eq('user_id',u.id).order('is_default',{ascending:false});if(error)throw error;let m=(ms||[]).find(v=>['active','ativo'].includes(String(v.status||'').toLowerCase()));if(!m)throw Error('Usuário autenticado, mas sem vínculo ativo com o tenant.');let [{data:r},{data:t},{data:c}]=await Promise.all([sb.from('roles').select('code,name').eq('id',m.role_id).maybeSingle(),sb.from('tenants').select('code,name').eq('id',m.tenant_id).maybeSingle(),m.company_id?sb.from('companies').select('code,trade_name,legal_name').eq('id',m.company_id).maybeSingle():Promise.resolve({data:null})]);return{user:u,m,r,t,c}}
function isAdmin(){return ['MASTER','SGQ'].includes(ctx?.r?.code)}
async function loadPortals(x){let {data:p}=await sb.from('sgq_external_portals').select('id,portal_name,portal_url,current_url,category,owner_name,system_code,environment,is_official,is_active,update_mode,check_frequency,status,last_checked_at,last_changed_at,content_scope,access_notes,notes').eq('tenant_id',x).order('portal_name');$('portalsList').innerHTML=p?.length?p.map(v=>{let u=v.current_url||v.portal_url,link=u?`<a class="btn alt" href="${esc(u)}" target="_blank" rel="noopener">Abrir portal</a>`:'<span class="tag warn">URL pendente</span>';let edit=isAdmin()?` <button class="btn alt" onclick='editPortal(${JSON.stringify(JSON.stringify(v))})'>Editar</button>`:'';return it(v.portal_name,`${v.system_code||v.category||'PORTAL'} · ${v.environment||'—'} · ${v.is_active?'ATIVO':'INATIVO'} · ${v.update_mode}/${v.check_frequency}`,`<div class="right" style="margin-top:8px">${link}${edit}</div>`) }).join(''):'<div class="empty">Nenhum portal visível.</div>'}
window.editPortal=s=>{let v=JSON.parse(s);$('pId').value=v.id||'';$('pName').value=v.portal_name||'';$('pCode').value=v.system_code||'';$('pUrl').value=v.portal_url||'';$('pEnv').value=v.environment||'EXTERNAL';$('pCategory').value=v.category||'SYSTEM';$('pOwner').value=v.owner_name||'';$('pScope').value=v.content_scope||'';$('pMode').value=v.update_mode||'MANUAL';$('pFreq').value=v.check_frequency||'MANUAL';$('pOfficial').checked=!!v.is_official;$('pActive').checked=!!v.is_active;$('pAccess').value=v.access_notes||'';$('pNotes').value=v.notes||'';$('portalMsg').textContent='Editando '+v.portal_name;window.scrollTo({top:$('adminPanel').offsetTop,behavior:'smooth'})};
async function loadAdmin(x){$('adminPanel').classList.toggle('hidden',!isAdmin());if(!isAdmin())return;let {data:us,error}=await sb.rpc('sgq_list_tenant_users',{p_tenant:x});$('xUser').innerHTML=error?'<option>Erro ao carregar usuários</option>':(us?.length?us.map(u=>`<option value="${u.user_id}">${esc(u.email)} · ${esc(u.role_code||'—')} · ${esc(u.membership_status)}</option>`).join(''):'<option value="">Nenhum usuário ativo cadastrado</option>');$('xModule').innerHTML=modsCache.map(m=>`<option value="${esc(m.code)}">${esc(m.name)} (${esc(m.code)})</option>`).join('')}
async function load(){let x=ctx.m.tenant_id;$('contextInfo').innerHTML=`<b>${esc(ctx.user.email)}</b><br>Tenant: ${esc(ctx.t?.name||ctx.t?.code||x)}<br>Empresa: ${esc(ctx.c?.trade_name||ctx.c?.legal_name||'Escopo do tenant')}<br>Papel: <b>${esc(ctx.r?.code||'—')}</b>`;$('userBadge').textContent=`${ctx.r?.code||'USUÁRIO'} · ${ctx.user.email}`;
let [{data:mods},a,al,ag,dc,au]=await Promise.all([sb.from('sgq_modules').select('code,name,module_group,status,automation_enabled,sync_priority').eq('tenant_id',x).eq('is_active',true).order('sync_priority'),cnt('rq045_actions',[['eq','tenant_id',x],['not','status','in','(closed,cancelled,verified)']]),cnt('sgq_alerts',[['eq','tenant_id',x],['eq','status','OPEN']]),cnt('sgq_calendar_items',[['eq','tenant_id',x],['not','status','in','(DONE,CANCELLED)']]),cnt('sgq_documents',[['eq','tenant_id',x]]),cnt('sgq_audits',[['eq','tenant_id',x]])]);modsCache=mods||[];
[['kModules',modsCache.length],['kActions',a],['kAlerts',al],['kAgenda',ag],['kDocs',dc],['kAudits',au]].forEach(([i,n])=>$(i).textContent=n??'—');$('modulesGrid').innerHTML=modsCache.length?modsCache.map(m=>`<div class="module" data-module-code="${esc(m.code)}"><h3>${esc(m.name)}</h3><p>${esc(m.code)} · ${esc(m.module_group||'SGQ')}</p><span class="tag ${m.automation_enabled?'ok':''}">${m.automation_enabled?'AUTOMATIZADO':esc(m.status)}</span></div>`).join(''):'<div class="empty">Nenhum módulo visível.</div>';
let [{data:as},{data:als},{data:gs}]=await Promise.all([sb.from('rq045_actions').select('code,title,status,priority,due_date').eq('tenant_id',x).order('created_at',{ascending:false}).limit(8),sb.from('sgq_alerts').select('title,severity,module_code,due_at').eq('tenant_id',x).eq('status','OPEN').order('created_at',{ascending:false}).limit(8),sb.from('sgq_calendar_items').select('title,module_code,due_at,status').eq('tenant_id',x).order('due_at',{ascending:true}).limit(8)]);$('actionsList').innerHTML=as?.length?as.map(v=>it(`${v.code} — ${v.title}`,`${v.status} · ${v.priority} · prazo ${fd(v.due_date)}`)).join(''):'<div class="empty">Sem ações visíveis.</div>';$('alertsList').innerHTML=als?.length?als.map(v=>it(v.title,`${v.module_code} · ${v.severity} · ${fd(v.due_at)}`)).join(''):'<div class="empty">Sem alertas.</div>';$('agendaList').innerHTML=gs?.length?gs.map(v=>it(v.title,`${v.module_code} · ${fd(v.due_at)} · ${v.status}`)).join(''):'<div class="empty">Sem itens de agenda.</div>';await Promise.all([loadPortals(x),loadAdmin(x)]);if(window.sgqDocsRefresh)await window.sgqDocsRefresh()}
async function enter(s){try{ctx=await context(s.user);$('loginPanel').classList.add('hidden');$('appPanel').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('gateText').textContent='Sessão autenticada; dados filtrados por RLS/RBAC.';$('gateTag').textContent='PILOTO CONECTADO';$('gateTag').className='tag ok';await load()}catch(e){$('loginMsg').textContent=e.message}}
async function leave(){ctx=null;$('loginPanel').classList.remove('hidden');$('appPanel').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('userBadge').textContent='Não autenticado'}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Autenticando...';let {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return $('loginMsg').textContent='Acesso não autorizado: '+error.message;await enter(data.session)});$('logoutBtn').onclick=async()=>{await sb.auth.signOut();await leave()};
$('actionForm').addEventListener('submit',async e=>{e.preventDefault();if(!ctx)return;let m=ctx.m;if(!m.company_id)return $('actionMsg').textContent='Vínculo sem empresa definida.';let code='RQ045-'+new Date().toISOString().replace(/\D/g,'').slice(0,14),p={tenant_id:m.tenant_id,company_id:m.company_id,code,origin:'SGQ_MANAGER',action_type:$('aType').value,title:$('aTitle').value.trim(),description:$('aDescription').value.trim(),owner_user_id:ctx.user.id,priority:$('aPriority').value,due_date:$('aDue').value,status:'open',evidence:{},metadata:{source:'SGQ_MANAGER_WEB'},created_by:ctx.user.id};$('actionMsg').textContent='Gravando...';let {error}=await sb.from('rq045_actions').insert(p);if(error)return $('actionMsg').textContent='Não gravado: '+error.message;$('actionMsg').textContent='Ação criada: '+code;e.target.reset();await load()});
$('portalForm').addEventListener('submit',async e=>{e.preventDefault();if(!ctx||!isAdmin())return;let a={p_tenant:ctx.m.tenant_id,p_id:$('pId').value||null,p_portal_name:$('pName').value.trim(),p_portal_url:$('pUrl').value.trim(),p_category:$('pCategory').value.trim()||'SYSTEM',p_owner_type:'SYSTEM_OWNER',p_owner_name:$('pOwner').value.trim(),p_system_code:$('pCode').value.trim(),p_environment:$('pEnv').value,p_content_scope:$('pScope').value.trim(),p_is_official:$('pOfficial').checked,p_is_active:$('pActive').checked,p_update_mode:$('pMode').value,p_check_frequency:$('pFreq').value,p_access_notes:$('pAccess').value.trim(),p_notes:$('pNotes').value.trim()};$('portalMsg').textContent='Salvando...';let {error}=await sb.rpc('sgq_upsert_external_portal',a);if(error)return $('portalMsg').textContent='Não salvo: '+error.message;$('portalMsg').textContent='Portal salvo com Audit Log.';e.target.reset();$('pId').value='';await loadPortals(ctx.m.tenant_id)});
$('accessForm').addEventListener('submit',async e=>{e.preventDefault();if(!ctx||!isAdmin())return;if(!$('xUser').value)return $('accessMsg').textContent='Cadastre primeiro um usuário ativo no tenant.';let a={p_tenant:ctx.m.tenant_id,p_module_code:$('xModule').value,p_user_id:$('xUser').value,p_access_level:$('xLevel').value,p_active:$('xActive').value==='true',p_reason:$('xReason').value.trim()};$('accessMsg').textContent='Aplicando...';let {error}=await sb.rpc('sgq_set_module_access',a);$('accessMsg').textContent=error?'Não aplicado: '+error.message:'Permissão atualizada e registrada no Audit Log.'});
(async()=>{let {data:{session}}=await sb.auth.getSession();session?await enter(session):await leave()})();
const DOC=document.createElement('script');DOC.src='doc-manager.js?v=20260819-r1';DOC.onload=()=>{const NAV=document.createElement('script');NAV.src='navigation.js?v=20260819-r1';NAV.onload=()=>{const FIX=document.createElement('script');FIX.src='functional-fix.js?v=20260819-r1';document.head.appendChild(FIX)};document.head.appendChild(NAV)};document.head.appendChild(DOC);