(()=>{
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const codeMap={GOV:'m02',DOC:'m05',KPI:'m32',IND:'m32',RQ045:'m08',AGEN:'m20',AGENDA:'m20',ALERT:'m19',AUD:'m34','5S':'m12',NC:'m13',NC_CAPA:'m13',RISK:'m04',EXTERNAL_PORTALS:'m23',ACCREDITATION_BODIES:'m10',CERTIFICATION_BODIES:'m10',TRN:'m35',TRAIN:'m35',CERT:'m10',INSP:'m37',INSPEC:'m37',SUPQ:'m11',PPAP:'m11',METRO:'m12',POS:'m14',POST:'m14',SEAL:'m36',SELOS:'m36',MNT:'m36',MAINT:'m36',EVID:'m17',BI:'m01',AGENTS:'m24'};
  const compMap={'Selos da Qualidade':'m36','Manutenções':'m36','Instalações':'m36','Preventivas':'m36','Pendências':'m19','Evidências':'m17','Metas':'m32','Resultados':'m32','Tendências':'m32','Análise crítica':'m32','Plano quando aplicável':'m33','Internas':'m34','Externas':'m34','Fornecedores':'m11','5S':'m12','Follow-up':'m34','Programação':'m35','Documento associado':'m05','Presença':'m35','Validade':'m35','Reciclagem':'m35','Desenhos':'m37','Especificações':'m37','Boletins':'m37','Certificados':'m10','Ensaios':'m37','Requisitos técnicos':'m37'};
  function nav(id){const b=q(`.navitem[data-target="${id}"]`);if(b){b.click();return true} location.hash=id;return false}
  window.sgqNavigateModule=(code)=>nav(codeMap[code]||code);

  function enhanceTenantModules(){qa('#modulesGrid .module').forEach(card=>{if(card.dataset.clickReady)return;card.dataset.clickReady='1';card.style.cursor='pointer';card.tabIndex=0;const p=card.querySelector('p')?.textContent||'';const code=p.split('·')[0].trim();card.title='Abrir módulo';card.addEventListener('click',()=>window.sgqNavigateModule(code));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();window.sgqNavigateModule(code)}});const btn=document.createElement('button');btn.type='button';btn.className='btn alt';btn.style.marginTop='10px';btn.textContent='Abrir módulo';btn.onclick=e=>{e.stopPropagation();window.sgqNavigateModule(code)};card.appendChild(btn)})}

  function enhanceComponents(){qa('#moduleBody .flow span').forEach(el=>{if(el.dataset.clickReady)return;el.dataset.clickReady='1';el.style.cursor='pointer';el.setAttribute('role','button');el.tabIndex=0;const go=()=>{const name=el.textContent.trim(),id=compMap[name];if(id)nav(id);else showComponent(name)};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}})}
  function showComponent(name){let box=q('#componentDetail');if(!box){box=document.createElement('div');box.id='componentDetail';box.className='box';box.style.marginTop='14px';q('#moduleBody')?.appendChild(box)}box.innerHTML=`<h3>${esc(name)}</h3><p class="muted">Componente selecionado. A operação utiliza os dados e permissões do módulo atual.</p>`}

  function rqPanel(){let p=q('#rqImportPanel');if(p)return p;p=document.createElement('section');p.id='rqImportPanel';p.className='form';p.style.marginTop='14px';p.innerHTML=`<h2>Importar RQs</h2><p class="muted">Importe um ou vários arquivos RQ. Os arquivos são gravados no repositório privado do tenant e registrados na Lista Mestra.</p><div class="row"><div class="field"><label>Tipo padrão</label><select id="rqImportType"><option value="RQ">RQ / Registro</option><option value="RQ002">RQ 002</option><option value="RQ007">RQ 007</option><option value="RQ045">RQ 045</option><option value="RQ176">RQ 176</option><option value="OTHER_RQ">Outro RQ</option></select></div><div class="field"><label>Status</label><select id="rqImportStatus"><option value="ACTIVE">Vigente</option><option value="DRAFT">Em desenvolvimento</option><option value="IN_REVIEW">Em revisão</option><option value="PENDING_APPROVAL">Em aprovação</option></select></div></div><div class="field"><label>Arquivos</label><input id="rqImportFiles" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.xlsm,.ppt,.pptx,.csv,.txt"></div><button id="rqImportBtn" class="btn" type="button">Importar RQs</button><div id="rqImportMsg" class="msg">Nenhum arquivo selecionado.</div><div id="rqImportList" class="list" style="margin-top:12px"></div>`;p.querySelector('#rqImportBtn').onclick=importRQs;return p}

  function safeName(s){return String(s||'arquivo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^_+|_+$/g,'')||'arquivo'}
  function parseRQ(filename,index){const stem=filename.replace(/\.[^.]+$/,'').trim();const m=stem.match(/\bRQ[\s_-]*0*(\d{1,4})\b/i);const num=m?String(Number(m[1])).padStart(3,'0'):null;return{code:num?`RQ ${num}`:`RQ IMP ${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${String(index+1).padStart(3,'0')}`,title:stem}}
  async function importRQs(){const msg=q('#rqImportMsg'),files=[...(q('#rqImportFiles')?.files||[])];if(!ctx)return msg.textContent='Faça login antes de importar.';if(!files.length)return msg.textContent='Selecione pelo menos um arquivo.';if(!ctx.m?.tenant_id)return msg.textContent='Tenant não identificado.';msg.textContent=`Importando ${files.length} arquivo(s)...`;let ok=0,errs=[];for(let i=0;i<files.length;i++){const f=files[i],info=parseRQ(f.name,i);try{const path=`${ctx.m.tenant_id}/rq/${Date.now()}_${i}_${safeName(f.name)}`;const up=await sb.storage.from('sgq-documents').upload(path,f,{upsert:false,contentType:f.type||undefined});if(up.error)throw up.error;const type=q('#rqImportType').value,status=q('#rqImportStatus').value;const current_file={bucket:'sgq-documents',path,name:f.name,size:f.size,mime:f.type||null};const payload={tenant_id:ctx.m.tenant_id,company_id:ctx.m.company_id||null,code:info.code,title:info.title,document_type:type,revision:'00',status,current_file,metadata:{source:'RQ_IMPORT_WEB',original_name:f.name,imported_at:new Date().toISOString()},created_by:ctx.user.id,updated_by:ctx.user.id};let ins=await sb.from('sgq_documents').insert(payload);if(ins.error){await sb.storage.from('sgq-documents').remove([path]);throw ins.error}ok++}catch(e){errs.push(`${f.name}: ${e.message||e}`)}}msg.textContent=errs.length?`Importados ${ok}/${files.length}. Falhas: ${errs.join(' | ')}`:`Importação concluída: ${ok} arquivo(s).`;if(window.sgqDocsRefresh)await window.sgqDocsRefresh();if(typeof load==='function')await load();}

  function mountRQ(){const z=q('#liveZone');if(!z)return;z.innerHTML='';z.appendChild(rqPanel());}
  document.addEventListener('click',e=>{const b=e.target.closest('.navitem[data-target]');if(b){setTimeout(()=>{enhanceComponents();if(b.dataset.target==='m22')mountRQ()},0)}});
  const mo=new MutationObserver(()=>{enhanceTenantModules();enhanceComponents()});mo.observe(document.documentElement,{subtree:true,childList:true});
  function init(){enhanceTenantModules();enhanceComponents();if(location.hash==='#m22')setTimeout(mountRQ,50)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();