(()=>{
'use strict';
window.AGENDA_MANAGER_R11=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let suggestions=[],lastSeen=null,meetings=[];
const uid=()=>typeof session!=='undefined'&&session?.user?.id?session.user.id:null;
const currentTenant=()=>typeof tenant!=='undefined'?tenant:null;
const coreData=()=>typeof data!=='undefined'&&data?data:{tasks:[],events:[],workspaces:[],calendars:[]};
const now=()=>new Date();
function style(){if(q('#r11style'))return;const s=document.createElement('style');s.id='r11style';s.textContent='.r11-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.r11-list{display:grid;gap:10px}.r11-actions{display:flex;gap:8px;flex-wrap:wrap}.r11-risk-critical{border-left:4px solid #d33}.r11-risk-high{border-left:4px solid #e67e22}.r11-risk-medium{border-left:4px solid #d4a017}.r11-risk-info{border-left:4px solid var(--ac)}.r11-mini{font-size:12px}.r11-kpi{font-size:24px;font-weight:800}.r11-note{padding:10px;border:1px solid var(--ln);border-radius:10px;background:var(--p2)}@media(max-width:850px){.r11-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function addPage(){if(q('#assistente'))return;const main=q('main.main')||q('main');if(!main)return;const sec=document.createElement('section');sec.id='assistente';sec.className='page';sec.innerHTML=`<div class="r11-grid"><div class="card"><div class="muted">Riscos altos/críticos</div><div id="r11RiskKpi" class="r11-kpi">0</div></div><div class="card"><div class="muted">Sugestões pendentes</div><div id="r11PendingKpi" class="r11-kpi">0</div></div><div class="card"><div class="muted">Mudanças desde o último acesso</div><div id="r11ChangesKpi" class="r11-kpi">0</div></div></div><div class="card section"><h3>Assistente Governado</h3><div class="r11-note"><b>Como funciona:</b> o motor usa regras explicáveis sobre prazos, prioridade, carga, agenda e registros estruturados. Ele recomenda; você decide. Nenhuma mudança relevante é aplicada sem confirmação.</div><div class="r11-actions section"><button class="btn primary" id="r11Analyze">Analisar agora</button><button class="btn" id="r11Weekly">Planejar semana</button><button class="btn" id="r11Changes">O que mudou?</button></div></div><div class="card section"><h3>Sugestões</h3><div id="r11Suggestions" class="r11-list"></div></div><div class="card section"><h3>Resumo de reunião</h3><div class="r11-actions"><select id="r11MeetingSelect" style="min-width:260px"></select><button class="btn" id="r11MeetingSummary">Gerar resumo estruturado</button></div><div id="r11MeetingOutput" class="section"></div></div>`;main.appendChild(sec);if(typeof navItems!=='undefined'&&!navItems.some(x=>x[0]==='assistente'))navItems.push(['assistente','✨ Assistente']);}
function tasks(){return (coreData().tasks||[]).filter(t=>!['completed','cancelled'].includes(t.status))}
function score(t){let s=0;const n=now();if(t.due_at){const h=(new Date(t.due_at)-n)/36e5;if(h<0)s+=100;else if(h<24)s+=70;else if(h<72)s+=40;else if(h<168)s+=20}if(t.priority==='critical')s+=60;else if(t.priority==='high')s+=35;else if(t.priority==='medium')s+=15;if(t.is_important)s+=20;if(!t.planned_start_at)s+=10;return s}
function level(v){return v>=120?'critical':v>=80?'high':v>=45?'medium':'info'}
async function saveSuggestion(type,title,summary,payload={},risk='info',ids=[]){const u=uid(),t=currentTenant();if(!u||!t)return;const {data:row,error}=await sb.from('agenda_ai_suggestions').insert({tenant_id:t,user_id:u,suggestion_type:type,title,summary,payload,risk_level:risk,status:'pending',source_scope:'agenda_manager',source_ids:ids}).select().single();if(error)throw error;return row}
async function logAction(sug,action,result,targetType=null,targetId=null,before=null,after=null){const u=uid(),t=currentTenant();if(!u||!t)return;await sb.from('agenda_ai_action_log').insert({tenant_id:t,user_id:u,suggestion_id:sug?.id||null,action_type:action,target_type:targetType,target_id:targetId,before_state:before,after_state:after,result})}
async function loadState(){const u=uid(),t=currentTenant();if(!u||!t)return;const [sg,st,mt]=await Promise.all([sb.from('agenda_ai_suggestions').select('*').eq('tenant_id',t).eq('user_id',u).order('generated_at',{ascending:false}).limit(30),sb.from('agenda_user_activity_state').select('*').eq('tenant_id',t).eq('user_id',u).maybeSingle(),sb.from('agenda_meetings').select('id,title,starts_at,status').eq('tenant_id',t).order('starts_at',{ascending:false}).limit(50)]);if(sg.error)throw sg.error;suggestions=sg.data||[];lastSeen=st.data?.last_seen_at||null;meetings=mt.data||[];render()}
function render(){const b=q('#r11Suggestions');if(!b)return;const pend=suggestions.filter(x=>x.status==='pending');q('#r11PendingKpi').textContent=pend.length;q('#r11RiskKpi').textContent=pend.filter(x=>['high','critical'].includes(x.risk_level)).length;b.innerHTML=pend.length?pend.map(s=>`<div class="item r11-risk-${esc(s.risk_level)}"><div class="grow"><b>${esc(s.title)}</b><div>${esc(s.summary)}</div><div class="muted r11-mini">${new Date(s.generated_at).toLocaleString('pt-BR')} · ${esc(s.risk_level)}</div></div><div class="r11-actions"><button class="btn primary r11Accept" data-id="${s.id}">Aceitar</button><button class="btn r11Edit" data-id="${s.id}">Ajustar</button><button class="btn r11Ignore" data-id="${s.id}">Ignorar</button></div></div>`).join(''):'<div class="empty">Nenhuma sugestão pendente.</div>';qa('.r11Accept',b).forEach(x=>x.onclick=()=>review(x.dataset.id,'accepted'));qa('.r11Ignore',b).forEach(x=>x.onclick=()=>review(x.dataset.id,'ignored'));qa('.r11Edit',b).forEach(x=>x.onclick=()=>editSuggestion(x.dataset.id));renderMeetingOptions()}
async function analyze(){const ts=tasks().map(t=>({...t,_score:score(t)})).sort((a,b)=>b._score-a._score),risky=ts.filter(t=>t._score>=45).slice(0,8);if(risky.length)await saveSuggestion('deadline_risk','Risco de atraso identificado',`${risky.length} atividade(s) merecem atenção por prazo, prioridade ou ausência de planejamento.`,{task_ids:risky.map(t=>t.id),scores:risky.map(t=>[t.id,t._score])},level(risky[0]._score),risky.map(t=>t.id));const unplanned=ts.filter(t=>!t.planned_start_at&&t._score>=20).slice(0,6);if(unplanned.length)await saveSuggestion('reorganize','Reorganização recomendada',`${unplanned.length} atividade(s) prioritárias ainda não possuem bloco de execução no calendário.`,{task_ids:unplanned.map(t=>t.id)},'medium',unplanned.map(t=>t.id));if(!risky.length&&!unplanned.length)await saveSuggestion('weekly_plan','Agenda sob controle','Não foram identificados riscos relevantes nas atividades abertas neste momento.',{},'info',[]);await loadState()}
async function weekly(){const top=tasks().map(t=>({...t,_score:score(t)})).sort((a,b)=>b._score-a._score).slice(0,10);if(!top.length)return alert('Não há tarefas abertas para planejar.');await saveSuggestion('weekly_plan','Plano inteligente da semana',`Priorizar ${top.length} atividade(s), começando pelas de maior risco e prazo. A aceitação adicionará essas atividades ao Meu Dia; os horários continuam sob sua decisão.`,{task_ids:top.map(t=>t.id)},'info',top.map(t=>t.id));await loadState()}
async function changes(){const u=uid(),t=currentTenant();if(!u||!t)return;const since=lastSeen?new Date(lastSeen):new Date(Date.now()-7*864e5),tables=[['Tarefas','agm_tasks'],['Eventos','agm_events'],['Projetos','agenda_projects'],['Reuniões','agenda_meetings'],['Decisões','agenda_decisions'],['Estudos','agenda_studies']];let total=0,parts=[];for(const [name,table] of tables){const {count,error}=await sb.from(table).select('*',{count:'exact',head:true}).eq('tenant_id',t).gte('updated_at',since.toISOString());if(!error&&count){total+=count;parts.push(`${name}: ${count}`)}}q('#r11ChangesKpi').textContent=total;const summary=total?`Desde ${since.toLocaleString('pt-BR')}: ${parts.join(' · ')}.`:'Nenhuma alteração relevante encontrada desde o último registro.';await saveSuggestion('changes_since_last_access','O que mudou desde seu último acesso?',summary,{since:since.toISOString(),total},'info',[]);await sb.from('agenda_user_activity_state').upsert({tenant_id:t,user_id:u,last_seen_at:new Date().toISOString(),last_digest_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'tenant_id,user_id'});lastSeen=new Date().toISOString();await loadState()}
async function review(id,status){const sug=suggestions.find(x=>x.id===id);if(!sug)return;if(status==='accepted'){if(sug.suggestion_type==='weekly_plan'){const ids=sug.payload?.task_ids||[];if(ids.length){const {error}=await sb.from('agm_tasks').update({is_my_day:true,updated_at:new Date().toISOString()}).in('id',ids);if(error)return alert(error.message);await logAction(sug,'accept_weekly_plan','applied','task',null,{task_ids:ids},{is_my_day:true})}}else if(sug.suggestion_type==='deadline_risk'){const ids=sug.payload?.task_ids||[];if(ids.length){const {error}=await sb.from('agm_tasks').update({is_important:true,updated_at:new Date().toISOString()}).in('id',ids);if(error)return alert(error.message);await logAction(sug,'prioritize_risk','applied','task',null,{task_ids:ids},{is_important:true})}}else if(sug.suggestion_type==='reorganize'){await logAction(sug,'open_planning','user_review_required');if(typeof go==='function')go('planejamento')}else await logAction(sug,'accept_suggestion','recorded')}const {error}=await sb.from('agenda_ai_suggestions').update({status,reviewed_at:new Date().toISOString(),reviewed_by:uid(),applied_at:status==='accepted'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);if(typeof reload==='function')await reload();await loadState()}
async function editSuggestion(id){const sug=suggestions.find(x=>x.id===id);if(!sug)return;const text=prompt('Ajuste a recomendação antes de registrar:',sug.summary);if(text===null)return;const {error}=await sb.from('agenda_ai_suggestions').update({summary:text,status:'edited',reviewed_at:new Date().toISOString(),reviewed_by:uid(),updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await logAction(sug,'edit_suggestion','recorded');await loadState()}
function renderMeetingOptions(){const s=q('#r11MeetingSelect');if(!s)return;s.innerHTML='<option value="">Selecione uma reunião</option>'+meetings.map(m=>`<option value="${m.id}">${esc(m.title)} · ${new Date(m.starts_at).toLocaleDateString('pt-BR')}</option>`).join('')}
async function meetingSummary(){const id=q('#r11MeetingSelect').value,t=currentTenant();if(!id||!t)return alert('Selecione uma reunião.');const [{data:m,error:me},{data:items},{data:decisions},{data:actions}]=await Promise.all([sb.from('agenda_meetings').select('*').eq('tenant_id',t).eq('id',id).single(),sb.from('agenda_meeting_items').select('*').eq('tenant_id',t).eq('meeting_id',id).order('item_order'),sb.from('agenda_decisions').select('*').eq('tenant_id',t).eq('meeting_id',id).order('created_at'),sb.from('agm_tasks').select('*').eq('tenant_id',t).eq('source_type','meeting').eq('source_id',id)]);if(me)return alert(me.message);const text=[`Reunião: ${m?.title||''}`,m?.objective?`Objetivo: ${m.objective}`:'',items?.length?`Pauta: ${items.map(x=>x.title).join('; ')}`:'',decisions?.length?`Decisões: ${decisions.map(x=>x.decision).join('; ')}`:'',actions?.length?`Ações: ${actions.map(x=>x.title).join('; ')}`:'',m?.summary?`Ata/Resumo: ${m.summary}`:''].filter(Boolean).join('\n');q('#r11MeetingOutput').innerHTML='<pre style="white-space:pre-wrap">'+esc(text)+'</pre>';await saveSuggestion('meeting_summary','Resumo estruturado da reunião',text,{meeting_id:id},'info',[id]);await loadState()}
function bind(){q('#r11Analyze')?.addEventListener('click',analyze);q('#r11Weekly')?.addEventListener('click',weekly);q('#r11Changes')?.addEventListener('click',changes);q('#r11MeetingSummary')?.addEventListener('click',meetingSummary)}
function wrapGo(){if(typeof go!=='function'||window.__r11Go)return;const base=go;go=function(id){base(id);if(id==='assistente')setTimeout(()=>loadState().catch(e=>console.warn('R11',e)),100)};window.__r11Go=true}
function boot(){style();addPage();bind();wrapGo();if(typeof nav==='function')nav();const sub=q('.side .sub');if(sub)sub.textContent='AMICO CONSULTYNG · v0.7 R11';setTimeout(()=>loadState().catch(()=>{}),700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();