(()=>{
'use strict';
window.AGENDA_MANAGER_R12=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>typeof session!=='undefined'&&session?.user?.id?session.user.id:null;
const currentTenant=()=>typeof tenant!=='undefined'?tenant:null;
const core=()=>typeof data!=='undefined'&&data?data:{tasks:[],events:[],workspaces:[],calendars:[]};
let ingestions=[],candidates=[],activeIngestion=null;

function style(){if(q('#r12style'))return;const s=document.createElement('style');s.id='r12style';s.textContent=`
.r12-drop{border:2px dashed var(--ln);border-radius:16px;padding:24px;text-align:center;background:var(--p2);cursor:pointer}.r12-drop.drag{border-color:var(--ac)}.r12-grid{display:grid;grid-template-columns:1.3fr .8fr .8fr .8fr;gap:8px;align-items:end}.r12-list{display:grid;gap:10px}.r12-candidate{display:grid;grid-template-columns:auto 1.8fr .8fr .8fr .8fr;gap:8px;align-items:center}.r12-meta{font-size:12px}.r12-actions{display:flex;gap:8px;flex-wrap:wrap}.r12-progress{height:7px;background:var(--ln);border-radius:99px;overflow:hidden}.r12-progress>i{display:block;height:100%;background:var(--ac);width:0;transition:.2s}.r12-pill{display:inline-block;padding:3px 7px;border:1px solid var(--ln);border-radius:999px;font-size:11px}.r12-history{display:grid;gap:7px}.r12-history .item{cursor:pointer}@media(max-width:900px){.r12-grid,.r12-candidate{grid-template-columns:1fr 1fr}}@media(max-width:560px){.r12-grid,.r12-candidate{grid-template-columns:1fr}.r12-candidate>input[type=checkbox]{justify-self:start}}
`;document.head.appendChild(s)}
function addPage(){if(q('#importar-arquivo'))return;const main=q('main.main')||q('main');if(!main)return;const sec=document.createElement('section');sec.id='importar-arquivo';sec.className='page';sec.innerHTML=`
<div class="card"><h3>📥 Importar arquivo e automatizar tarefas</h3><div class="muted">Envie TXT, MD, CSV, JSON, PDF, DOCX ou XLSX (até 25 MB). A Agenda lê o conteúdo, identifica possíveis tarefas e mostra uma prévia antes da distribuição.</div><div id="r12Drop" class="r12-drop section"><b>Arraste o arquivo aqui</b><div class="muted">ou toque para selecionar</div><input id="r12File" type="file" hidden accept=".txt,.md,.csv,.json,.pdf,.docx,.xlsx,text/plain,text/markdown,text/csv,application/json,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></div><div class="r12-progress"><i id="r12Bar"></i></div><div id="r12Status" class="muted section"></div></div>
<div class="card section"><div class="r12-actions"><h3 style="margin-right:auto">Prévia da análise</h3><button class="btn" id="r12SelectAll">Selecionar todas</button><button class="btn primary" id="r12Distribute">Aprovar e distribuir</button></div><div id="r12Summary" class="muted"></div><div id="r12Candidates" class="r12-list section"></div></div>
<div class="card section"><h3>Arquivos processados</h3><div id="r12History" class="r12-history"></div></div>`;main.appendChild(sec);if(typeof navItems!=='undefined'&&!navItems.some(x=>x[0]==='importar-arquivo'))navItems.push(['importar-arquivo','📥 Importar arquivo']);}
function injectButtons(){for(const page of ['dashboard','inbox']){const root=q('#'+page);if(!root||q('.r12UploadQuick',root))continue;const card=q('.card',root)||root;const b=document.createElement('button');b.className='btn primary r12UploadQuick';b.type='button';b.textContent='📥 Importar arquivo';b.style.marginBottom='10px';b.onclick=()=>typeof go==='function'&&go('importar-arquivo');card.insertBefore(b,card.firstChild)}}
function msg(t,bad=false){const e=q('#r12Status');if(e){e.textContent=t;e.style.color=bad?'#ff8f8f':''}}
function progress(n){const b=q('#r12Bar');if(b)b.style.width=Math.max(0,Math.min(100,n))+'%'}
async function loadHistory(){if(!uid()||!currentTenant())return;const {data:rows,error}=await sb.from('agenda_file_ingestions').select('*').eq('tenant_id',currentTenant()).eq('user_id',uid()).order('created_at',{ascending:false}).limit(20);if(error)throw error;ingestions=rows||[];renderHistory()}
function renderHistory(){const b=q('#r12History');if(!b)return;b.innerHTML=ingestions.length?ingestions.map(x=>`<div class="item" data-ing="${x.id}"><div class="grow"><b>${esc(x.file_name)}</b><div class="muted r12-meta">${new Date(x.created_at).toLocaleString('pt-BR')} · ${esc(x.status)} · ${esc(x.analysis_summary||x.error_message||'')}</div></div><span class="r12-pill">${esc(x.mime_type||'arquivo')}</span></div>`).join(''):'<div class="empty">Nenhum arquivo processado.</div>';qa('[data-ing]',b).forEach(x=>x.onclick=()=>openIngestion(x.dataset.ing))}
async function openIngestion(id){activeIngestion=ingestions.find(x=>x.id===id)||null;if(!activeIngestion){const {data}=await sb.from('agenda_file_ingestions').select('*').eq('id',id).single();activeIngestion=data||null}const {data:rows,error}=await sb.from('agenda_file_task_candidates').select('*').eq('ingestion_id',id).order('confidence',{ascending:false});if(error)throw error;candidates=rows||[];renderCandidates();if(typeof go==='function')go('importar-arquivo')}
function renderCandidates(){const sum=q('#r12Summary'),b=q('#r12Candidates');if(!b)return;if(sum)sum.textContent=activeIngestion?.analysis_summary||'';const visible=candidates.filter(c=>['suggested','approved'].includes(c.status));b.innerHTML=visible.length?visible.map(c=>`<div class="item r12-candidate" data-cid="${c.id}"><input class="r12Pick" type="checkbox" checked><div><input class="r12Title" value="${esc(c.title)}"><div class="muted r12-meta">Confiança ${Math.round(Number(c.confidence||0)*100)}%${c.owner_hint?' · Responsável citado: '+esc(c.owner_hint):''}</div><div class="muted r12-meta">${esc(c.source_excerpt||'')}</div></div><div class="field"><label>Destino</label><select class="r12Dest"><option value="inbox" ${c.destination==='inbox'?'selected':''}>Inbox</option><option value="my_day" ${c.destination==='my_day'?'selected':''}>Meu Dia</option><option value="project" ${c.destination==='project'?'selected':''}>Projeto</option><option value="study" ${c.destination==='study'?'selected':''}>Estudo</option><option value="calendar" ${c.destination==='calendar'?'selected':''}>Agenda</option></select></div><div class="field"><label>Prioridade</label><select class="r12Priority"><option value="low" ${c.priority==='low'?'selected':''}>Baixa</option><option value="medium" ${c.priority==='medium'?'selected':''}>Média</option><option value="high" ${c.priority==='high'?'selected':''}>Alta</option><option value="critical" ${c.priority==='critical'?'selected':''}>Crítica</option></select></div><div class="field"><label>Prazo</label><input class="r12Due" type="date" value="${c.due_at?new Date(c.due_at).toISOString().slice(0,10):''}"></div></div>`).join(''):'<div class="empty">Nenhuma tarefa sugerida neste arquivo.</div>'}
function cleanName(n){return n.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
async function upload(file){if(!file)return;if(!uid()||!currentTenant())return msg('Entre no sistema antes de importar arquivos.',true);if(file.size>25*1024*1024)return msg('Arquivo maior que 25 MB.',true);const ext=(file.name.split('.').pop()||'').toLowerCase();if(!['txt','md','csv','json','pdf','docx','xlsx'].includes(ext))return msg('Formato não suportado nesta versão.',true);try{progress(8);msg('Enviando arquivo com segurança…');const id=crypto.randomUUID(),path=`${currentTenant()}/${uid()}/${id}/${cleanName(file.name)}`;const up=await sb.storage.from('agenda-uploads').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;progress(35);const ws=core().workspaces?.[0]?.id||null;const {data:ing,error:ierr}=await sb.from('agenda_file_ingestions').insert({id,tenant_id:currentTenant(),user_id:uid(),workspace_id:ws,file_name:file.name,mime_type:file.type||null,file_size:file.size,storage_path:path,status:'uploaded'}).select().single();if(ierr)throw ierr;activeIngestion=ing;msg('Arquivo recebido. Lendo e analisando…');progress(50);const {data:result,error:ferr}=await sb.functions.invoke('agenda-file-analyze',{body:{ingestion_id:id}});if(ferr||result?.error)throw new Error(result?.error||ferr.message);progress(88);await loadHistory();await openIngestion(id);progress(100);msg(result.summary||'Análise concluída. Revise e aprove as tarefas.');setTimeout(()=>progress(0),900)}catch(e){progress(0);msg(e?.message||String(e),true)}}
async function distribute(){if(!activeIngestion)return alert('Selecione ou envie um arquivo.');const rows=qa('[data-cid]').filter(r=>q('.r12Pick',r)?.checked);if(!rows.length)return alert('Selecione ao menos uma tarefa.');if(!confirm(`Criar e distribuir ${rows.length} tarefa(s) a partir deste arquivo?`))return;msg('Distribuindo tarefas aprovadas…');let created=0;for(const r of rows){const cid=r.dataset.cid,c=candidates.find(x=>x.id===cid);if(!c)continue;const title=q('.r12Title',r).value.trim();if(!title)continue;const dest=q('.r12Dest',r).value,priority=q('.r12Priority',r).value,dueVal=q('.r12Due',r).value;const due=dueVal?new Date(dueVal+'T23:59:00').toISOString():null;let projectId=null,studyId=null;if(dest==='project'){const {data:p}=await sb.from('agenda_projects').select('id').eq('tenant_id',currentTenant()).neq('status','completed').order('created_at',{ascending:false}).limit(1).maybeSingle();projectId=p?.id||null}if(dest==='study'){const {data:s}=await sb.from('agenda_studies').select('id').eq('tenant_id',currentTenant()).eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle();studyId=s?.id||null}const isToday=dueVal===new Date().toISOString().slice(0,10);const taskRow={tenant_id:currentTenant(),workspace_id:core().workspaces?.[0]?.id||null,owner_id:uid(),assignee_id:uid(),title,description:c.description||c.source_excerpt||null,priority,status:'created',due_at:due,source_type:'file',source_id:activeIngestion.id,project_id:projectId,study_id:studyId,context_type:c.context_type||'Arquivo',context_label:activeIngestion.file_name,is_inbox:dest==='inbox'||((dest==='project'&&!projectId)||(dest==='study'&&!studyId)),is_my_day:dest==='my_day'||isToday,is_important:['high','critical'].includes(priority)};const {data:t,error}=await sb.from('agm_tasks').insert(taskRow).select().single();if(error){console.error(error);continue}if(dest==='calendar'&&due){const cal=core().calendars?.[0];if(cal){const end=new Date(due),start=new Date(end.getTime()-60*60000);await sb.from('agm_events').insert({tenant_id:currentTenant(),calendar_id:cal.id,workspace_id:taskRow.workspace_id,task_id:t.id,owner_id:uid(),title,starts_at:start.toISOString(),ends_at:end.toISOString(),status:'planned',visibility:'private',description:'Criado a partir de '+activeIngestion.file_name})}}await sb.from('agenda_file_task_candidates').update({status:'created',task_id:t.id,title,priority,destination:dest,due_at:due,reviewed_at:new Date().toISOString()}).eq('id',cid);created++}await sb.from('agenda_file_ingestions').update({status:'approved',approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',activeIngestion.id);if(typeof reload==='function')await reload();await loadHistory();await openIngestion(activeIngestion.id);msg(`${created} tarefa(s) criada(s) e distribuída(s).`);alert(`${created} tarefa(s) distribuída(s) com sucesso.`)}
function bind(){const drop=q('#r12Drop'),file=q('#r12File');drop?.addEventListener('click',()=>file?.click());file?.addEventListener('change',()=>upload(file.files?.[0]));drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');upload(e.dataTransfer?.files?.[0])});q('#r12SelectAll')?.addEventListener('click',()=>qa('.r12Pick').forEach(x=>x.checked=true));q('#r12Distribute')?.addEventListener('click',distribute)}
function wrapGo(){if(typeof go!=='function'||window.__r12Go)return;const base=go;go=function(id){base(id);if(id==='importar-arquivo')setTimeout(loadHistory,100)};window.__r12Go=true}
function boot(){style();addPage();injectButtons();bind();wrapGo();if(typeof nav==='function')nav();const sub=q('.side .sub');if(sub)sub.textContent='AMICO CONSULTYNG · v0.8 R12';setTimeout(()=>loadHistory().catch(()=>{}),800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();