(()=>{'use strict';window.AGENDA_MANAGER_R14=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const modules=[['dashboard','Dashboard'],['meu-dia','Meu Dia'],['inbox','Caixa de Entrada'],['agenda','Agenda'],['tarefas','Tarefas'],['workspaces','Workspaces'],['planejamento','Planejamento'],['projetos','Projetos'],['reunioes','Reuniões'],['estudos','Estudos'],['componentes','Componentes Vivos'],['busca','Busca Global'],['assistente','Assistente Governado'],['importar-arquivo','Importar Arquivo'],['planos','Planos e Licenciamento'],['integracoes','Integrações'],['admin','Administração']];
let checks=[];
function addStyle(){if(q('#r14style'))return;const s=document.createElement('style');s.id='r14style';s.textContent=`.r14-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.r14-table{width:100%;border-collapse:collapse}.r14-table th,.r14-table td{border-bottom:1px solid var(--ln);padding:9px;vertical-align:top;text-align:left}.r14-table select,.r14-table input{min-width:125px}.r14-progress{height:10px;background:var(--p2);border-radius:99px;overflow:hidden}.r14-progress span{display:block;height:100%;background:var(--ac)}.r14-outline .card,.r14-outline button,.r14-outline input,.r14-outline select,.r14-outline textarea{outline:2px dashed #f6b73c!important;outline-offset:2px}.r14-note{width:100%;min-width:180px}.r14-small{font-size:12px;color:var(--mu)}@media(max-width:900px){.r14-grid{grid-template-columns:repeat(2,1fr)}.r14-table{font-size:12px}.r14-table th:nth-child(5),.r14-table td:nth-child(5){display:none}}@media(max-width:560px){.r14-grid{grid-template-columns:1fr}.r14-table{display:block;overflow:auto}}`;document.head.appendChild(s)}
function normalizeCopy(){document.querySelectorAll('.sub').forEach(x=>{if(/AMICO CONSULTYNG/.test(x.textContent||''))x.textContent='AMICO CONSULTYNG · Agenda Manager R14'});const auth=q('#auth .muted');if(auth)auth.textContent='AMICO CONSULTYNG · Agenda Manager Online · R14';const gate=[...document.querySelectorAll('#admin h3')].find(x=>/Gate R06/i.test(x.textContent||''));if(gate)gate.textContent='Status de homologação';}
function addPage(){if(q('#homologacao'))return;const main=q('main.main')||q('main');if(!main)return;const s=document.createElement('section');s.id='homologacao';s.className='page';s.innerHTML=`<div class="card"><h3>🧪 Homologação Visual e de Escrita</h3><p class="muted">Percorra cada módulo, valide apresentação, textos e funcionamento e registre o resultado. A homologação fica vinculada ao seu usuário e ambiente.</p><div class="r14-grid"><div class="card"><div class="muted">Módulos</div><div class="metric" id="r14Total">${modules.length}</div></div><div class="card"><div class="muted">Aprovados</div><div class="metric" id="r14Approved">0</div></div><div class="card"><div class="muted">Ajustar</div><div class="metric" id="r14Adjust">0</div></div><div class="card"><div class="muted">Progresso</div><div class="metric" id="r14Pct">0%</div></div></div><div class="section r14-progress"><span id="r14Bar" style="width:0%"></span></div><div class="actions section"><button class="btn primary" id="r14Start">Iniciar validação</button><button class="btn" id="r14Visual">Destacar elementos visuais</button><button class="btn" id="r14Copy">Copiar relatório</button><button class="btn" id="r14Reset">Limpar minha validação</button></div></div><div class="card section"><div style="overflow:auto"><table class="r14-table"><thead><tr><th>Módulo</th><th>Visual</th><th>Escrita</th><th>Função</th><th>Observação</th><th>Abrir</th></tr></thead><tbody id="r14Rows"></tbody></table></div></div><div class="card section"><h3>Critério rápido</h3><div class="r14-small">Visual: alinhamento, espaçamento, contraste, responsividade e clareza. Escrita: português, acentuação, termos consistentes e mensagens compreensíveis. Função: botão/campo executa o que promete, sem erro ou tela vazia.</div></div>`;main.appendChild(s);if(typeof navItems!=='undefined'&&!navItems.some(x=>x[0]==='homologacao'))navItems.push(['homologacao','🧪 Homologação']);bind();renderRows();}
async function load(){if(!window.sb||!window.tenant||!window.session)return;const {data,error}=await sb.from('agenda_validation_checks').select('*').eq('tenant_id',tenant).eq('user_id',session.user.id);if(!error)checks=data||[];renderRows()}
function rowFor(k,l){return checks.find(x=>x.module_key===k)||{module_key:k,module_label:l,visual_status:'not_tested',text_status:'not_tested',function_status:'not_tested',notes:''}}
function sel(v,type,k){return `<select data-kind="${type}" data-key="${k}"><option value="not_tested" ${v==='not_tested'?'selected':''}>Não testado</option><option value="approved" ${v==='approved'?'selected':''}>Aprovado</option><option value="adjust" ${v==='adjust'?'selected':''}>Ajustar</option></select>`}
function renderRows(){const body=q('#r14Rows');if(!body)return;body.innerHTML=modules.map(([k,l])=>{const r=rowFor(k,l);return `<tr><td><b>${esc(l)}</b></td><td>${sel(r.visual_status,'visual_status',k)}</td><td>${sel(r.text_status,'text_status',k)}</td><td>${sel(r.function_status,'function_status',k)}</td><td><input class="r14-note" data-note="${k}" value="${esc(r.notes||'')}" placeholder="Ex.: corrigir título / botão desalinhado"></td><td><button class="btn" data-open="${k}">Abrir</button></td></tr>`}).join('');qa('[data-kind]',body).forEach(x=>x.onchange=()=>save(x.dataset.key));qa('[data-note]',body).forEach(x=>x.onchange=()=>save(x.dataset.note));qa('[data-open]',body).forEach(x=>x.onclick=()=>{if(typeof go==='function')go(x.dataset.open)});summary()}
async function save(k){if(!window.sb||!window.tenant||!window.session)return;const l=modules.find(x=>x[0]===k)?.[1]||k;const visual=q(`[data-kind="visual_status"][data-key="${k}"]`)?.value||'not_tested',text=q(`[data-kind="text_status"][data-key="${k}"]`)?.value||'not_tested',func=q(`[data-kind="function_status"][data-key="${k}"]`)?.value||'not_tested',notes=q(`[data-note="${k}"]`)?.value||'';const {error}=await sb.from('agenda_validation_checks').upsert({tenant_id:tenant,user_id:session.user.id,module_key:k,module_label:l,visual_status:visual,text_status:text,function_status:func,notes,updated_at:new Date().toISOString()},{onConflict:'tenant_id,user_id,module_key'});if(error)return alert(error.message);const i=checks.findIndex(x=>x.module_key===k),obj={module_key:k,module_label:l,visual_status:visual,text_status:text,function_status:func,notes};if(i>=0)checks[i]={...checks[i],...obj};else checks.push(obj);summary()}
function summary(){let approved=0,adjust=0,tested=0;modules.forEach(([k,l])=>{const r=rowFor(k,l),vals=[r.visual_status,r.text_status,r.function_status];if(vals.every(x=>x==='approved'))approved++;if(vals.some(x=>x==='adjust'))adjust++;if(vals.every(x=>x!=='not_tested'))tested++});const pct=Math.round(tested/modules.length*100);if(q('#r14Approved'))q('#r14Approved').textContent=approved;if(q('#r14Adjust'))q('#r14Adjust').textContent=adjust;if(q('#r14Pct'))q('#r14Pct').textContent=pct+'%';if(q('#r14Bar'))q('#r14Bar').style.width=pct+'%'}
function report(){const lines=['AGENDA MANAGER R14 — HOMOLOGAÇÃO VISUAL, TEXTUAL E FUNCIONAL',''];modules.forEach(([k,l])=>{const r=rowFor(k,l);lines.push(`${l} | Visual: ${r.visual_status} | Escrita: ${r.text_status} | Função: ${r.function_status}${r.notes?' | Obs.: '+r.notes:''}`)});return lines.join('\n')}
function bind(){q('#r14Start')?.addEventListener('click',()=>{const first=modules.find(([k,l])=>{const r=rowFor(k,l);return [r.visual_status,r.text_status,r.function_status].includes('not_tested')});if(first&&typeof go==='function')go(first[0])});q('#r14Visual')?.addEventListener('click',()=>document.body.classList.toggle('r14-outline'));q('#r14Copy')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(report());alert('Relatório copiado.')});q('#r14Reset')?.addEventListener('click',async()=>{if(!confirm('Limpar toda a sua homologação?'))return;const {error}=await sb.from('agenda_validation_checks').delete().eq('tenant_id',tenant).eq('user_id',session.user.id);if(error)return alert(error.message);checks=[];renderRows()})}
function addQuickButton(){const a=q('.top .actions');if(!a||q('#r14Quick'))return;const b=document.createElement('button');b.id='r14Quick';b.className='btn';b.textContent='🧪 Validar';b.onclick=()=>go('homologacao');a.prepend(b)}
function wrapInit(){if(typeof init!=='function'||window.__r14Init)return;const base=init;init=async function(){await base();normalizeCopy();addQuickButton();await load().catch(()=>{})};window.__r14Init=true}
function boot(){addStyle();normalizeCopy();addPage();addQuickButton();wrapInit();if(typeof nav==='function')nav();setTimeout(()=>load().catch(()=>{}),700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();